<Project Sdk="Pe.Revit.Sdk">

    <PropertyGroup>
        <PeProjectKind>RevitLibrary</PeProjectKind>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Pe.Revit.Partition</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NetTopologySuite" Version="2.6.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pe.Revit.Space\Pe.Revit.Space.csproj"/>
    </ItemGroup>

</Project>
