// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from BridgeOpCatalog bridge operations.
// One Effect RPC per generated bridge operation. Generic host.call remains for agent compatibility.

import { Schema, type Effect } from "effect";
import { Rpc, type RpcClient } from "effect/unstable/rpc";
import type { HostOperationKey } from "../contracts/host-operations.generated.js";
import type { HostOpRequest, HostOpResponse } from "../operation-types.js";
import { HostRpcError } from "../rpc-error.js";
import * as schemas from "./host-effect.generated.js";

export const bridgeOperationRpcs = [
  Rpc.make("revit.apply.document.open", {
    payload: {
      request: schemas.openRevitDocumentRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.openRevitDocumentDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.apply.parameters-service-cache.refresh", {
    payload: { bridgeSessionId: Schema.optional(Schema.String) },
    success: schemas.parametersServiceCacheDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.concept-evidence", {
    payload: {
      request: schemas.conceptEvidenceRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.conceptEvidenceDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-circuits", {
    payload: {
      request: schemas.electricalCircuitsCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.electricalCircuitsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-load-classifications", {
    payload: {
      request: schemas.electricalLoadClassificationsCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.electricalLoadClassificationsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-panels", {
    payload: {
      request: schemas.electricalPanelsCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.electricalPanelsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families", {
    payload: {
      request: schemas.loadedFamiliesCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.loadedFamiliesCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families.filter-field-options", {
    payload: {
      request: schemas.loadedFamiliesFilterFieldOptionsRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.fieldOptionsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families.filter-schema", {
    payload: { bridgeSessionId: Schema.optional(Schema.String) },
    success: schemas.schemaDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.parameter-bindings", {
    payload: {
      request: schemas.projectParameterBindingsRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.projectParameterBindingsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.parameter-evidence", {
    payload: {
      request: schemas.parameterEvidenceRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.parameterEvidenceDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.project-browser", {
    payload: {
      request: schemas.projectBrowserRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.projectBrowserDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.project-index", {
    payload: {
      request: schemas.projectIndexRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.projectIndexDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.schedules", {
    payload: {
      request: schemas.scheduleCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scheduleCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.document-session", {
    payload: { bridgeSessionId: Schema.optional(Schema.String) },
    success: schemas.revitDocumentSessionContextDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.summary", {
    payload: { bridgeSessionId: Schema.optional(Schema.String) },
    success: schemas.revitAgentContextSummaryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.view-rendering-state", {
    payload: {
      request: schemas.revitAgentViewRenderingStateRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.revitAgentViewRenderingStateDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.visible-summary", {
    payload: {
      request: schemas.revitAgentVisibleContextRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.revitAgentVisibleContextDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.electrical-panel-schedules", {
    payload: {
      request: schemas.electricalPanelSchedulesQueryRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.electricalPanelSchedulesQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.elements", {
    payload: {
      request: schemas.elementContextQueryRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.elementContextQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.schedules", {
    payload: {
      request: schemas.scheduleQueryRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scheduleQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.sheets", {
    payload: {
      request: schemas.sheetDetailRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.sheetDetailDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.loaded-families", {
    payload: {
      request: schemas.loadedFamiliesMatrixRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.loadedFamiliesMatrixDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.parameter-coverage", {
    payload: {
      request: schemas.parameterCoverageRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.parameterCoverageDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.schedule-coverage", {
    payload: {
      request: schemas.scheduleCoverageRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scheduleCoverageDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.schedule-profiles", {
    payload: {
      request: schemas.scheduleProfilesQueryRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scheduleProfilesQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.resolve.references", {
    payload: {
      request: schemas.revitAgentContextResolveRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.revitAgentContextResolveDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.execute", {
    payload: {
      request: schemas.executeRevitScriptRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.executeRevitScriptDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.pod.export", {
    payload: {
      request: schemas.scriptPodExportRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scriptPodExportDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.pod.import", {
    payload: {
      request: schemas.scriptPodImportRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scriptPodImportDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.workspace.bootstrap", {
    payload: {
      request: schemas.scriptWorkspaceBootstrapRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.scriptWorkspaceBootstrapDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.field-options", {
    payload: {
      request: schemas.fieldOptionsRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.fieldOptionsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.parameter-catalog", {
    payload: {
      request: schemas.parameterCatalogRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.parameterCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.schema", {
    payload: {
      request: schemas.schemaRequestSchema,
      bridgeSessionId: Schema.optional(Schema.String),
    },
    success: schemas.schemaDataSchema,
    error: HostRpcError,
  }),
] as const;

export type BridgeOperationRpcClient<E = never> = RpcClient.RpcClient.Flat<
  (typeof bridgeOperationRpcs)[number],
  E
>;

export function callBridgeOperationRpcMember<E>(
  client: BridgeOperationRpcClient<E>,
  key: HostOperationKey,
  request: unknown,
  bridgeSessionId?: string,
): Effect.Effect<unknown, HostRpcError | E> {
  switch (key) {
    case "revit.apply.document.open":
      return client("revit.apply.document.open", {
        request: request as Schema.Schema.Type<typeof schemas.openRevitDocumentRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.apply.parameters-service-cache.refresh":
      return client(
        "revit.apply.parameters-service-cache.refresh",
        bridgeSessionId ? { bridgeSessionId } : {},
      );
    case "revit.catalog.concept-evidence":
      return client("revit.catalog.concept-evidence", {
        request: request as Schema.Schema.Type<typeof schemas.conceptEvidenceRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.electrical-circuits":
      return client("revit.catalog.electrical-circuits", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalCircuitsCatalogRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.electrical-load-classifications":
      return client("revit.catalog.electrical-load-classifications", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalLoadClassificationsCatalogRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.electrical-panels":
      return client("revit.catalog.electrical-panels", {
        request: request as Schema.Schema.Type<typeof schemas.electricalPanelsCatalogRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.loaded-families":
      return client("revit.catalog.loaded-families", {
        request: request as Schema.Schema.Type<typeof schemas.loadedFamiliesCatalogRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.loaded-families.filter-field-options":
      return client("revit.catalog.loaded-families.filter-field-options", {
        request: request as Schema.Schema.Type<
          typeof schemas.loadedFamiliesFilterFieldOptionsRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.loaded-families.filter-schema":
      return client(
        "revit.catalog.loaded-families.filter-schema",
        bridgeSessionId ? { bridgeSessionId } : {},
      );
    case "revit.catalog.parameter-bindings":
      return client("revit.catalog.parameter-bindings", {
        request: request as Schema.Schema.Type<
          typeof schemas.projectParameterBindingsRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.parameter-evidence":
      return client("revit.catalog.parameter-evidence", {
        request: request as Schema.Schema.Type<typeof schemas.parameterEvidenceRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.project-browser":
      return client("revit.catalog.project-browser", {
        request: request as Schema.Schema.Type<typeof schemas.projectBrowserRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.project-index":
      return client("revit.catalog.project-index", {
        request: request as Schema.Schema.Type<typeof schemas.projectIndexRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.catalog.schedules":
      return client("revit.catalog.schedules", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleCatalogRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.context.document-session":
      return client("revit.context.document-session", bridgeSessionId ? { bridgeSessionId } : {});
    case "revit.context.summary":
      return client("revit.context.summary", bridgeSessionId ? { bridgeSessionId } : {});
    case "revit.context.view-rendering-state":
      return client("revit.context.view-rendering-state", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentViewRenderingStateRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.context.visible-summary":
      return client("revit.context.visible-summary", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentVisibleContextRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.detail.electrical-panel-schedules":
      return client("revit.detail.electrical-panel-schedules", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalPanelSchedulesQueryRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.detail.elements":
      return client("revit.detail.elements", {
        request: request as Schema.Schema.Type<typeof schemas.elementContextQueryRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.detail.schedules":
      return client("revit.detail.schedules", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleQueryRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.detail.sheets":
      return client("revit.detail.sheets", {
        request: request as Schema.Schema.Type<typeof schemas.sheetDetailRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.matrix.loaded-families":
      return client("revit.matrix.loaded-families", {
        request: request as Schema.Schema.Type<typeof schemas.loadedFamiliesMatrixRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.matrix.parameter-coverage":
      return client("revit.matrix.parameter-coverage", {
        request: request as Schema.Schema.Type<typeof schemas.parameterCoverageRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.matrix.schedule-coverage":
      return client("revit.matrix.schedule-coverage", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleCoverageRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.matrix.schedule-profiles":
      return client("revit.matrix.schedule-profiles", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleProfilesQueryRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "revit.resolve.references":
      return client("revit.resolve.references", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentContextResolveRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "scripting.execute":
      return client("scripting.execute", {
        request: request as Schema.Schema.Type<typeof schemas.executeRevitScriptRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "scripting.pod.export":
      return client("scripting.pod.export", {
        request: request as Schema.Schema.Type<typeof schemas.scriptPodExportRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "scripting.pod.import":
      return client("scripting.pod.import", {
        request: request as Schema.Schema.Type<typeof schemas.scriptPodImportRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "scripting.workspace.bootstrap":
      return client("scripting.workspace.bootstrap", {
        request: request as Schema.Schema.Type<
          typeof schemas.scriptWorkspaceBootstrapRequestSchema
        >,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "settings.field-options":
      return client("settings.field-options", {
        request: request as Schema.Schema.Type<typeof schemas.fieldOptionsRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "settings.parameter-catalog":
      return client("settings.parameter-catalog", {
        request: request as Schema.Schema.Type<typeof schemas.parameterCatalogRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
    case "settings.schema":
      return client("settings.schema", {
        request: request as Schema.Schema.Type<typeof schemas.schemaRequestSchema>,
        ...(bridgeSessionId ? { bridgeSessionId } : {}),
      });
  }
}

export type BridgeOperationRpcHandler = <K extends HostOperationKey>(
  key: K,
  request: HostOpRequest<K>,
  bridgeSessionId?: string,
) => Effect.Effect<HostOpResponse<K>, HostRpcError>;

export function makeBridgeOperationRpcHandlers(handle: BridgeOperationRpcHandler) {
  return {
    "revit.apply.document.open": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.openRevitDocumentRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.apply.document.open", payload.request, payload.bridgeSessionId),
    "revit.apply.parameters-service-cache.refresh": (payload: {
      readonly bridgeSessionId?: string;
    }) =>
      handle("revit.apply.parameters-service-cache.refresh", undefined, payload.bridgeSessionId),
    "revit.catalog.concept-evidence": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.conceptEvidenceRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.concept-evidence", payload.request, payload.bridgeSessionId),
    "revit.catalog.electrical-circuits": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.electricalCircuitsCatalogRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.electrical-circuits", payload.request, payload.bridgeSessionId),
    "revit.catalog.electrical-load-classifications": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.electricalLoadClassificationsCatalogRequestSchema
      >;
      readonly bridgeSessionId?: string;
    }) =>
      handle(
        "revit.catalog.electrical-load-classifications",
        payload.request,
        payload.bridgeSessionId,
      ),
    "revit.catalog.electrical-panels": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.electricalPanelsCatalogRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.electrical-panels", payload.request, payload.bridgeSessionId),
    "revit.catalog.loaded-families": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.loadedFamiliesCatalogRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.loaded-families", payload.request, payload.bridgeSessionId),
    "revit.catalog.loaded-families.filter-field-options": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.loadedFamiliesFilterFieldOptionsRequestSchema
      >;
      readonly bridgeSessionId?: string;
    }) =>
      handle(
        "revit.catalog.loaded-families.filter-field-options",
        payload.request,
        payload.bridgeSessionId,
      ),
    "revit.catalog.loaded-families.filter-schema": (payload: {
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.loaded-families.filter-schema", undefined, payload.bridgeSessionId),
    "revit.catalog.parameter-bindings": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectParameterBindingsRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.parameter-bindings", payload.request, payload.bridgeSessionId),
    "revit.catalog.parameter-evidence": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterEvidenceRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.parameter-evidence", payload.request, payload.bridgeSessionId),
    "revit.catalog.project-browser": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectBrowserRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.project-browser", payload.request, payload.bridgeSessionId),
    "revit.catalog.project-index": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectIndexRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.project-index", payload.request, payload.bridgeSessionId),
    "revit.catalog.schedules": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleCatalogRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.catalog.schedules", payload.request, payload.bridgeSessionId),
    "revit.context.document-session": (payload: { readonly bridgeSessionId?: string }) =>
      handle("revit.context.document-session", undefined, payload.bridgeSessionId),
    "revit.context.summary": (payload: { readonly bridgeSessionId?: string }) =>
      handle("revit.context.summary", undefined, payload.bridgeSessionId),
    "revit.context.view-rendering-state": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.revitAgentViewRenderingStateRequestSchema
      >;
      readonly bridgeSessionId?: string;
    }) => handle("revit.context.view-rendering-state", payload.request, payload.bridgeSessionId),
    "revit.context.visible-summary": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.revitAgentVisibleContextRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.context.visible-summary", payload.request, payload.bridgeSessionId),
    "revit.detail.electrical-panel-schedules": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.electricalPanelSchedulesQueryRequestSchema
      >;
      readonly bridgeSessionId?: string;
    }) =>
      handle("revit.detail.electrical-panel-schedules", payload.request, payload.bridgeSessionId),
    "revit.detail.elements": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.elementContextQueryRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.detail.elements", payload.request, payload.bridgeSessionId),
    "revit.detail.schedules": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleQueryRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.detail.schedules", payload.request, payload.bridgeSessionId),
    "revit.detail.sheets": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.sheetDetailRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.detail.sheets", payload.request, payload.bridgeSessionId),
    "revit.matrix.loaded-families": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.loadedFamiliesMatrixRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.matrix.loaded-families", payload.request, payload.bridgeSessionId),
    "revit.matrix.parameter-coverage": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterCoverageRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.matrix.parameter-coverage", payload.request, payload.bridgeSessionId),
    "revit.matrix.schedule-coverage": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleCoverageRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.matrix.schedule-coverage", payload.request, payload.bridgeSessionId),
    "revit.matrix.schedule-profiles": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleProfilesQueryRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.matrix.schedule-profiles", payload.request, payload.bridgeSessionId),
    "revit.resolve.references": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.revitAgentContextResolveRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("revit.resolve.references", payload.request, payload.bridgeSessionId),
    "scripting.execute": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.executeRevitScriptRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("scripting.execute", payload.request, payload.bridgeSessionId),
    "scripting.pod.export": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptPodExportRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("scripting.pod.export", payload.request, payload.bridgeSessionId),
    "scripting.pod.import": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptPodImportRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("scripting.pod.import", payload.request, payload.bridgeSessionId),
    "scripting.workspace.bootstrap": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptWorkspaceBootstrapRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("scripting.workspace.bootstrap", payload.request, payload.bridgeSessionId),
    "settings.field-options": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.fieldOptionsRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("settings.field-options", payload.request, payload.bridgeSessionId),
    "settings.parameter-catalog": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterCatalogRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("settings.parameter-catalog", payload.request, payload.bridgeSessionId),
    "settings.schema": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.schemaRequestSchema>;
      readonly bridgeSessionId?: string;
    }) => handle("settings.schema", payload.request, payload.bridgeSessionId),
  } as const;
}
