// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from BridgeOpCatalog bridge operations.
// One Effect RPC per generated bridge operation. Generic host.call remains for agent compatibility.

import { Schema, type Effect } from "effect";
import { Rpc, type RpcClient } from "effect/unstable/rpc";
import type { HostOperationKey } from "../contracts/host-operations.generated.js";
import type { HostOpRequest, HostOpResponse } from "../operation-types.js";
import { HostRpcError } from "../rpc-error.js";
import * as schemas from "./host-effect.generated.js";

export const bridgeOperationRpcs = [
  Rpc.make("revit.apply.document.open", {
    payload: { request: schemas.openRevitDocumentRequestSchema },
    success: schemas.openRevitDocumentDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.apply.parameters-service-cache.refresh", {
    payload: {},
    success: schemas.parametersServiceCacheDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.concept-evidence", {
    payload: { request: schemas.conceptEvidenceRequestSchema },
    success: schemas.conceptEvidenceDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-circuits", {
    payload: { request: schemas.electricalCircuitsCatalogRequestSchema },
    success: schemas.electricalCircuitsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-load-classifications", {
    payload: { request: schemas.electricalLoadClassificationsCatalogRequestSchema },
    success: schemas.electricalLoadClassificationsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.electrical-panels", {
    payload: { request: schemas.electricalPanelsCatalogRequestSchema },
    success: schemas.electricalPanelsCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families", {
    payload: { request: schemas.loadedFamiliesCatalogRequestSchema },
    success: schemas.loadedFamiliesCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families.filter-field-options", {
    payload: { request: schemas.loadedFamiliesFilterFieldOptionsRequestSchema },
    success: schemas.fieldOptionsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.loaded-families.filter-schema", {
    payload: {},
    success: schemas.schemaDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.parameter-bindings", {
    payload: { request: schemas.projectParameterBindingsRequestSchema },
    success: schemas.projectParameterBindingsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.parameter-evidence", {
    payload: { request: schemas.parameterEvidenceRequestSchema },
    success: schemas.parameterEvidenceDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.project-browser", {
    payload: { request: schemas.projectBrowserRequestSchema },
    success: schemas.projectBrowserDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.project-index", {
    payload: { request: schemas.projectIndexRequestSchema },
    success: schemas.projectIndexDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.catalog.schedules", {
    payload: { request: schemas.scheduleCatalogRequestSchema },
    success: schemas.scheduleCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.document-session", {
    payload: {},
    success: schemas.revitDocumentSessionContextDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.summary", {
    payload: {},
    success: schemas.revitAgentContextSummaryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.view-rendering-state", {
    payload: { request: schemas.revitAgentViewRenderingStateRequestSchema },
    success: schemas.revitAgentViewRenderingStateDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.context.visible-summary", {
    payload: { request: schemas.revitAgentVisibleContextRequestSchema },
    success: schemas.revitAgentVisibleContextDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.electrical-panel-schedules", {
    payload: { request: schemas.electricalPanelSchedulesQueryRequestSchema },
    success: schemas.electricalPanelSchedulesQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.elements", {
    payload: { request: schemas.elementContextQueryRequestSchema },
    success: schemas.elementContextQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.schedules", {
    payload: { request: schemas.scheduleQueryRequestSchema },
    success: schemas.scheduleQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.detail.sheets", {
    payload: { request: schemas.sheetDetailRequestSchema },
    success: schemas.sheetDetailDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.loaded-families", {
    payload: { request: schemas.loadedFamiliesMatrixRequestSchema },
    success: schemas.loadedFamiliesMatrixDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.parameter-coverage", {
    payload: { request: schemas.parameterCoverageRequestSchema },
    success: schemas.parameterCoverageDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.schedule-coverage", {
    payload: { request: schemas.scheduleCoverageRequestSchema },
    success: schemas.scheduleCoverageDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.matrix.schedule-profiles", {
    payload: { request: schemas.scheduleProfilesQueryRequestSchema },
    success: schemas.scheduleProfilesQueryDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("revit.resolve.references", {
    payload: { request: schemas.revitAgentContextResolveRequestSchema },
    success: schemas.revitAgentContextResolveDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.execute", {
    payload: { request: schemas.executeRevitScriptRequestSchema },
    success: schemas.executeRevitScriptDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.pod.export", {
    payload: { request: schemas.scriptPodExportRequestSchema },
    success: schemas.scriptPodExportDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.pod.import", {
    payload: { request: schemas.scriptPodImportRequestSchema },
    success: schemas.scriptPodImportDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("scripting.workspace.bootstrap", {
    payload: { request: schemas.scriptWorkspaceBootstrapRequestSchema },
    success: schemas.scriptWorkspaceBootstrapDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.field-options", {
    payload: { request: schemas.fieldOptionsRequestSchema },
    success: schemas.fieldOptionsDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.parameter-catalog", {
    payload: { request: schemas.parameterCatalogRequestSchema },
    success: schemas.parameterCatalogDataSchema,
    error: HostRpcError,
  }),
  Rpc.make("settings.schema", {
    payload: { request: schemas.schemaRequestSchema },
    success: schemas.schemaDataSchema,
    error: HostRpcError,
  }),
] as const;

export type BridgeOperationRpcClient<E = never> = RpcClient.RpcClient.Flat<
  (typeof bridgeOperationRpcs)[number],
  E
>;

export function callBridgeOperationRpcMember<E>(
  client: BridgeOperationRpcClient<E>,
  key: HostOperationKey,
  request: unknown,
): Effect.Effect<unknown, HostRpcError | E> {
  switch (key) {
    case "revit.apply.document.open":
      return client("revit.apply.document.open", {
        request: request as Schema.Schema.Type<typeof schemas.openRevitDocumentRequestSchema>,
      });
    case "revit.apply.parameters-service-cache.refresh":
      return client("revit.apply.parameters-service-cache.refresh", {});
    case "revit.catalog.concept-evidence":
      return client("revit.catalog.concept-evidence", {
        request: request as Schema.Schema.Type<typeof schemas.conceptEvidenceRequestSchema>,
      });
    case "revit.catalog.electrical-circuits":
      return client("revit.catalog.electrical-circuits", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalCircuitsCatalogRequestSchema
        >,
      });
    case "revit.catalog.electrical-load-classifications":
      return client("revit.catalog.electrical-load-classifications", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalLoadClassificationsCatalogRequestSchema
        >,
      });
    case "revit.catalog.electrical-panels":
      return client("revit.catalog.electrical-panels", {
        request: request as Schema.Schema.Type<typeof schemas.electricalPanelsCatalogRequestSchema>,
      });
    case "revit.catalog.loaded-families":
      return client("revit.catalog.loaded-families", {
        request: request as Schema.Schema.Type<typeof schemas.loadedFamiliesCatalogRequestSchema>,
      });
    case "revit.catalog.loaded-families.filter-field-options":
      return client("revit.catalog.loaded-families.filter-field-options", {
        request: request as Schema.Schema.Type<
          typeof schemas.loadedFamiliesFilterFieldOptionsRequestSchema
        >,
      });
    case "revit.catalog.loaded-families.filter-schema":
      return client("revit.catalog.loaded-families.filter-schema", {});
    case "revit.catalog.parameter-bindings":
      return client("revit.catalog.parameter-bindings", {
        request: request as Schema.Schema.Type<
          typeof schemas.projectParameterBindingsRequestSchema
        >,
      });
    case "revit.catalog.parameter-evidence":
      return client("revit.catalog.parameter-evidence", {
        request: request as Schema.Schema.Type<typeof schemas.parameterEvidenceRequestSchema>,
      });
    case "revit.catalog.project-browser":
      return client("revit.catalog.project-browser", {
        request: request as Schema.Schema.Type<typeof schemas.projectBrowserRequestSchema>,
      });
    case "revit.catalog.project-index":
      return client("revit.catalog.project-index", {
        request: request as Schema.Schema.Type<typeof schemas.projectIndexRequestSchema>,
      });
    case "revit.catalog.schedules":
      return client("revit.catalog.schedules", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleCatalogRequestSchema>,
      });
    case "revit.context.document-session":
      return client("revit.context.document-session", {});
    case "revit.context.summary":
      return client("revit.context.summary", {});
    case "revit.context.view-rendering-state":
      return client("revit.context.view-rendering-state", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentViewRenderingStateRequestSchema
        >,
      });
    case "revit.context.visible-summary":
      return client("revit.context.visible-summary", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentVisibleContextRequestSchema
        >,
      });
    case "revit.detail.electrical-panel-schedules":
      return client("revit.detail.electrical-panel-schedules", {
        request: request as Schema.Schema.Type<
          typeof schemas.electricalPanelSchedulesQueryRequestSchema
        >,
      });
    case "revit.detail.elements":
      return client("revit.detail.elements", {
        request: request as Schema.Schema.Type<typeof schemas.elementContextQueryRequestSchema>,
      });
    case "revit.detail.schedules":
      return client("revit.detail.schedules", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleQueryRequestSchema>,
      });
    case "revit.detail.sheets":
      return client("revit.detail.sheets", {
        request: request as Schema.Schema.Type<typeof schemas.sheetDetailRequestSchema>,
      });
    case "revit.matrix.loaded-families":
      return client("revit.matrix.loaded-families", {
        request: request as Schema.Schema.Type<typeof schemas.loadedFamiliesMatrixRequestSchema>,
      });
    case "revit.matrix.parameter-coverage":
      return client("revit.matrix.parameter-coverage", {
        request: request as Schema.Schema.Type<typeof schemas.parameterCoverageRequestSchema>,
      });
    case "revit.matrix.schedule-coverage":
      return client("revit.matrix.schedule-coverage", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleCoverageRequestSchema>,
      });
    case "revit.matrix.schedule-profiles":
      return client("revit.matrix.schedule-profiles", {
        request: request as Schema.Schema.Type<typeof schemas.scheduleProfilesQueryRequestSchema>,
      });
    case "revit.resolve.references":
      return client("revit.resolve.references", {
        request: request as Schema.Schema.Type<
          typeof schemas.revitAgentContextResolveRequestSchema
        >,
      });
    case "scripting.execute":
      return client("scripting.execute", {
        request: request as Schema.Schema.Type<typeof schemas.executeRevitScriptRequestSchema>,
      });
    case "scripting.pod.export":
      return client("scripting.pod.export", {
        request: request as Schema.Schema.Type<typeof schemas.scriptPodExportRequestSchema>,
      });
    case "scripting.pod.import":
      return client("scripting.pod.import", {
        request: request as Schema.Schema.Type<typeof schemas.scriptPodImportRequestSchema>,
      });
    case "scripting.workspace.bootstrap":
      return client("scripting.workspace.bootstrap", {
        request: request as Schema.Schema.Type<
          typeof schemas.scriptWorkspaceBootstrapRequestSchema
        >,
      });
    case "settings.field-options":
      return client("settings.field-options", {
        request: request as Schema.Schema.Type<typeof schemas.fieldOptionsRequestSchema>,
      });
    case "settings.parameter-catalog":
      return client("settings.parameter-catalog", {
        request: request as Schema.Schema.Type<typeof schemas.parameterCatalogRequestSchema>,
      });
    case "settings.schema":
      return client("settings.schema", {
        request: request as Schema.Schema.Type<typeof schemas.schemaRequestSchema>,
      });
  }
}

export type BridgeOperationRpcHandler = <K extends HostOperationKey>(
  key: K,
  request: HostOpRequest<K>,
) => Effect.Effect<HostOpResponse<K>, HostRpcError>;

export function makeBridgeOperationRpcHandlers(handle: BridgeOperationRpcHandler) {
  return {
    "revit.apply.document.open": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.openRevitDocumentRequestSchema>;
    }) => handle("revit.apply.document.open", payload.request),
    "revit.apply.parameters-service-cache.refresh": () =>
      handle("revit.apply.parameters-service-cache.refresh", undefined),
    "revit.catalog.concept-evidence": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.conceptEvidenceRequestSchema>;
    }) => handle("revit.catalog.concept-evidence", payload.request),
    "revit.catalog.electrical-circuits": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.electricalCircuitsCatalogRequestSchema>;
    }) => handle("revit.catalog.electrical-circuits", payload.request),
    "revit.catalog.electrical-load-classifications": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.electricalLoadClassificationsCatalogRequestSchema
      >;
    }) => handle("revit.catalog.electrical-load-classifications", payload.request),
    "revit.catalog.electrical-panels": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.electricalPanelsCatalogRequestSchema>;
    }) => handle("revit.catalog.electrical-panels", payload.request),
    "revit.catalog.loaded-families": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.loadedFamiliesCatalogRequestSchema>;
    }) => handle("revit.catalog.loaded-families", payload.request),
    "revit.catalog.loaded-families.filter-field-options": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.loadedFamiliesFilterFieldOptionsRequestSchema
      >;
    }) => handle("revit.catalog.loaded-families.filter-field-options", payload.request),
    "revit.catalog.loaded-families.filter-schema": () =>
      handle("revit.catalog.loaded-families.filter-schema", undefined),
    "revit.catalog.parameter-bindings": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectParameterBindingsRequestSchema>;
    }) => handle("revit.catalog.parameter-bindings", payload.request),
    "revit.catalog.parameter-evidence": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterEvidenceRequestSchema>;
    }) => handle("revit.catalog.parameter-evidence", payload.request),
    "revit.catalog.project-browser": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectBrowserRequestSchema>;
    }) => handle("revit.catalog.project-browser", payload.request),
    "revit.catalog.project-index": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.projectIndexRequestSchema>;
    }) => handle("revit.catalog.project-index", payload.request),
    "revit.catalog.schedules": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleCatalogRequestSchema>;
    }) => handle("revit.catalog.schedules", payload.request),
    "revit.context.document-session": () => handle("revit.context.document-session", undefined),
    "revit.context.summary": () => handle("revit.context.summary", undefined),
    "revit.context.view-rendering-state": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.revitAgentViewRenderingStateRequestSchema
      >;
    }) => handle("revit.context.view-rendering-state", payload.request),
    "revit.context.visible-summary": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.revitAgentVisibleContextRequestSchema>;
    }) => handle("revit.context.visible-summary", payload.request),
    "revit.detail.electrical-panel-schedules": (payload: {
      readonly request: Schema.Schema.Type<
        typeof schemas.electricalPanelSchedulesQueryRequestSchema
      >;
    }) => handle("revit.detail.electrical-panel-schedules", payload.request),
    "revit.detail.elements": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.elementContextQueryRequestSchema>;
    }) => handle("revit.detail.elements", payload.request),
    "revit.detail.schedules": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleQueryRequestSchema>;
    }) => handle("revit.detail.schedules", payload.request),
    "revit.detail.sheets": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.sheetDetailRequestSchema>;
    }) => handle("revit.detail.sheets", payload.request),
    "revit.matrix.loaded-families": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.loadedFamiliesMatrixRequestSchema>;
    }) => handle("revit.matrix.loaded-families", payload.request),
    "revit.matrix.parameter-coverage": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterCoverageRequestSchema>;
    }) => handle("revit.matrix.parameter-coverage", payload.request),
    "revit.matrix.schedule-coverage": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleCoverageRequestSchema>;
    }) => handle("revit.matrix.schedule-coverage", payload.request),
    "revit.matrix.schedule-profiles": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scheduleProfilesQueryRequestSchema>;
    }) => handle("revit.matrix.schedule-profiles", payload.request),
    "revit.resolve.references": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.revitAgentContextResolveRequestSchema>;
    }) => handle("revit.resolve.references", payload.request),
    "scripting.execute": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.executeRevitScriptRequestSchema>;
    }) => handle("scripting.execute", payload.request),
    "scripting.pod.export": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptPodExportRequestSchema>;
    }) => handle("scripting.pod.export", payload.request),
    "scripting.pod.import": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptPodImportRequestSchema>;
    }) => handle("scripting.pod.import", payload.request),
    "scripting.workspace.bootstrap": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.scriptWorkspaceBootstrapRequestSchema>;
    }) => handle("scripting.workspace.bootstrap", payload.request),
    "settings.field-options": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.fieldOptionsRequestSchema>;
    }) => handle("settings.field-options", payload.request),
    "settings.parameter-catalog": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.parameterCatalogRequestSchema>;
    }) => handle("settings.parameter-catalog", payload.request),
    "settings.schema": (payload: {
      readonly request: Schema.Schema.Type<typeof schemas.schemaRequestSchema>;
    }) => handle("settings.schema", payload.request),
  } as const;
}
