// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from BridgeOpCatalog bridge operations.
// Maps each bridge operation key to generated Effect schemas for TS host runtime validation.

import type { Schema } from "effect";
import type { HostOperationKey } from "../contracts/host-operations.generated.js";
import * as schemas from "./host-effect.generated.js";

type HostEffectOperationSchemaEntry = {
  request?: Schema.Codec<unknown>;
  response?: Schema.Codec<unknown>;
};

export const hostEffectOperationSchemas = {
  "revit.apply.document.open": {
    request: schemas.openRevitDocumentRequestSchema,
    response: schemas.openRevitDocumentDataSchema,
  },
  "revit.apply.parameters-service-cache.refresh": {
    response: schemas.parametersServiceCacheDataSchema,
  },
  "revit.catalog.concept-evidence": {
    request: schemas.conceptEvidenceRequestSchema,
    response: schemas.conceptEvidenceDataSchema,
  },
  "revit.catalog.electrical-circuits": {
    request: schemas.electricalCircuitsCatalogRequestSchema,
    response: schemas.electricalCircuitsCatalogDataSchema,
  },
  "revit.catalog.electrical-load-classifications": {
    request: schemas.electricalLoadClassificationsCatalogRequestSchema,
    response: schemas.electricalLoadClassificationsCatalogDataSchema,
  },
  "revit.catalog.electrical-panels": {
    request: schemas.electricalPanelsCatalogRequestSchema,
    response: schemas.electricalPanelsCatalogDataSchema,
  },
  "revit.catalog.loaded-families": {
    request: schemas.loadedFamiliesCatalogRequestSchema,
    response: schemas.loadedFamiliesCatalogDataSchema,
  },
  "revit.catalog.loaded-families.filter-field-options": {
    request: schemas.loadedFamiliesFilterFieldOptionsRequestSchema,
    response: schemas.fieldOptionsDataSchema,
  },
  "revit.catalog.loaded-families.filter-schema": { response: schemas.schemaDataSchema },
  "revit.catalog.parameter-bindings": {
    request: schemas.projectParameterBindingsRequestSchema,
    response: schemas.projectParameterBindingsDataSchema,
  },
  "revit.catalog.parameter-evidence": {
    request: schemas.parameterEvidenceRequestSchema,
    response: schemas.parameterEvidenceDataSchema,
  },
  "revit.catalog.project-browser": {
    request: schemas.projectBrowserRequestSchema,
    response: schemas.projectBrowserDataSchema,
  },
  "revit.catalog.project-index": {
    request: schemas.projectIndexRequestSchema,
    response: schemas.projectIndexDataSchema,
  },
  "revit.catalog.schedules": {
    request: schemas.scheduleCatalogRequestSchema,
    response: schemas.scheduleCatalogDataSchema,
  },
  "revit.context.document-session": { response: schemas.revitDocumentSessionContextDataSchema },
  "revit.context.summary": { response: schemas.revitAgentContextSummaryDataSchema },
  "revit.context.view-rendering-state": {
    request: schemas.revitAgentViewRenderingStateRequestSchema,
    response: schemas.revitAgentViewRenderingStateDataSchema,
  },
  "revit.context.visible-summary": {
    request: schemas.revitAgentVisibleContextRequestSchema,
    response: schemas.revitAgentVisibleContextDataSchema,
  },
  "revit.detail.electrical-panel-schedules": {
    request: schemas.electricalPanelSchedulesQueryRequestSchema,
    response: schemas.electricalPanelSchedulesQueryDataSchema,
  },
  "revit.detail.elements": {
    request: schemas.elementContextQueryRequestSchema,
    response: schemas.elementContextQueryDataSchema,
  },
  "revit.detail.schedules": {
    request: schemas.scheduleQueryRequestSchema,
    response: schemas.scheduleQueryDataSchema,
  },
  "revit.detail.sheets": {
    request: schemas.sheetDetailRequestSchema,
    response: schemas.sheetDetailDataSchema,
  },
  "revit.matrix.loaded-families": {
    request: schemas.loadedFamiliesMatrixRequestSchema,
    response: schemas.loadedFamiliesMatrixDataSchema,
  },
  "revit.matrix.parameter-coverage": {
    request: schemas.parameterCoverageRequestSchema,
    response: schemas.parameterCoverageDataSchema,
  },
  "revit.matrix.schedule-coverage": {
    request: schemas.scheduleCoverageRequestSchema,
    response: schemas.scheduleCoverageDataSchema,
  },
  "revit.matrix.schedule-profiles": {
    request: schemas.scheduleProfilesQueryRequestSchema,
    response: schemas.scheduleProfilesQueryDataSchema,
  },
  "revit.resolve.references": {
    request: schemas.revitAgentContextResolveRequestSchema,
    response: schemas.revitAgentContextResolveDataSchema,
  },
  "scripting.execute": {
    request: schemas.executeRevitScriptRequestSchema,
    response: schemas.executeRevitScriptDataSchema,
  },
  "scripting.pod.export": {
    request: schemas.scriptPodExportRequestSchema,
    response: schemas.scriptPodExportDataSchema,
  },
  "scripting.pod.import": {
    request: schemas.scriptPodImportRequestSchema,
    response: schemas.scriptPodImportDataSchema,
  },
  "scripting.workspace.bootstrap": {
    request: schemas.scriptWorkspaceBootstrapRequestSchema,
    response: schemas.scriptWorkspaceBootstrapDataSchema,
  },
  "settings.field-options": {
    request: schemas.fieldOptionsRequestSchema,
    response: schemas.fieldOptionsDataSchema,
  },
  "settings.parameter-catalog": {
    request: schemas.parameterCatalogRequestSchema,
    response: schemas.parameterCatalogDataSchema,
  },
  "settings.schema": { request: schemas.schemaRequestSchema, response: schemas.schemaDataSchema },
} as const satisfies Record<HostOperationKey, HostEffectOperationSchemaEntry>;
