using Pe.Dev.RevitAutomation;
using Pe.Shared.HostContracts.Operations;
using System.IO;
using System.Text;

namespace Pe.Dev.Cli;

internal static class PeaHostClientSyncCli {
    private static readonly GeneratedHostClientOperation[] HostClientOperations = [
        new("getProbe", GetHostProbeOperationContract.Definition),
        new("getSessionSummary", GetHostSessionSummaryOperationContract.Definition),
        new("getLogs", GetHostLogsOperationContract.Definition)
    ];

    private static readonly GeneratedHostClientOperation[] ScriptingClientOperations = [
        new("bootstrapWorkspace", GetScriptWorkspaceBootstrapOperationContract.Definition),
        new("execute", ExecuteRevitScriptOperationContract.Definition)
    ];

    public static async Task<int> RunAsync(
        IReadOnlyList<string> forwardedArguments,
        string? repoRootOverride,
        CancellationToken cancellationToken
    ) {
        PeaHostClientSyncOptions options;
        string repoRoot;
        try {
            options = PeaHostClientSyncOptions.Parse(forwardedArguments);
            ValidatePeaClientOperations();
            repoRoot = RepoRootResolver.Resolve(repoRootOverride);
        } catch (Exception ex) {
            Console.Error.WriteLine(ex.Message);
            return 10;
        }

        var typescriptPath = Path.Combine(repoRoot, "source", "pea", "app", "generated", "pe-host-client.ts");
        var generatedFiles = new[] {
            new GeneratedPeaClientFile(typescriptPath, GenerateTypeScriptClient())
        };

        if (options.Check)
            return await CheckAsync(repoRoot, generatedFiles, cancellationToken);

        foreach (var generatedFile in generatedFiles) {
            Directory.CreateDirectory(Path.GetDirectoryName(generatedFile.Path)!);
            await File.WriteAllTextAsync(generatedFile.Path, generatedFile.Content, cancellationToken);
            Console.WriteLine($"Generated {Path.GetRelativePath(repoRoot, generatedFile.Path)}");
        }

        return 0;
    }

    private static async Task<int> CheckAsync(
        string repoRoot,
        IReadOnlyList<GeneratedPeaClientFile> generatedFiles,
        CancellationToken cancellationToken
    ) {
        var staleFiles = new List<string>();
        foreach (var generatedFile in generatedFiles) {
            var relativePath = Path.GetRelativePath(repoRoot, generatedFile.Path);
            if (!File.Exists(generatedFile.Path)) {
                staleFiles.Add($"{relativePath} (missing)");
                continue;
            }

            var existingContent = await File.ReadAllTextAsync(generatedFile.Path, cancellationToken);
            if (!string.Equals(existingContent, generatedFile.Content, StringComparison.Ordinal))
                staleFiles.Add(relativePath);
        }

        if (staleFiles.Count == 0) {
            Console.WriteLine("Generated pea host client is current.");
            return 0;
        }

        Console.Error.WriteLine("Generated pea host client is stale:");
        foreach (var staleFile in staleFiles)
            Console.Error.WriteLine($"  {staleFile}");
        Console.Error.WriteLine("Run `pe-dev revit sync-pea-host-client` to update it.");
        return 1;
    }

    private static string GenerateTypeScriptClient() => $$"""
        // <auto-generated />
        // Generated by `pe-dev revit sync-pea-host-client` from HostOperationsCatalog.PeaClientSlice.

        export type HostHttpVerb = "GET" | "POST";
        export type HostExecutionMode = "Local" | "Bridge";

        export interface HostOperationDefinition {
          key: string;
          verb: HostHttpVerb;
          route: string;
          executionMode: HostExecutionMode;
        }

        {{RenderTypeScriptOperationGroup("hostOperations", HostClientOperations)}}

        {{RenderTypeScriptOperationGroup("scriptingOperations", ScriptingClientOperations)}}

        export interface HostModuleDescriptor {
          moduleKey: string;
          defaultRootKey: string;
          scope: "Host" | "Session" | "ActiveDocument";
          activeDocumentKind: "Any" | "ProjectOnly" | "FamilyOnly";
        }

        export interface HostActiveDocumentSummary {
          title?: string;
          key?: string;
          path?: string;
          isFamilyDocument: boolean;
          isWorkshared: boolean;
          isModelInCloud: boolean;
          cloudProjectGuid?: string;
          cloudModelGuid?: string;
          cloudModelUrn?: string;
          observedAtUnixMs: number;
        }

        export interface HostProbeData {
          runtimeIdentity: string;
          hostContractVersion: number;
          bridgeContractVersion: number;
          bridgePath: string;
          bridgeIsConnected: boolean;
          disconnectReason?: string;
        }

        export interface HostSessionSummaryData {
          bridgeIsConnected: boolean;
          sessionId?: string;
          processId?: number;
          revitVersion?: string;
          runtimeFramework?: string;
          openDocumentCount: number;
          activeDocument?: HostActiveDocumentSummary;
          availableModules: HostModuleDescriptor[];
        }

        export type HostLogTarget = "Host" | "Revit" | "All";

        export interface HostLogsRequest {
          target?: HostLogTarget;
          tailLineCount?: number;
        }

        export interface HostLogFileData {
          label: string;
          filePath: string;
          lines: string[];
        }

        export interface HostLogsData {
          files: HostLogFileData[];
        }

        export interface ScriptWorkspaceBootstrapRequest {
          workspaceKey?: string;
          createSampleScript?: boolean;
        }

        export interface ScriptWorkspaceBootstrapData {
          workspaceKey: string;
          workspaceRootPath: string;
          projectFilePath: string;
          sampleScriptPath: string;
          readmePath: string;
          revitVersion: string;
          targetFramework: string;
          runtimeAssemblyPath: string;
          generatedFiles: string[];
        }

        export type ScriptExecutionSourceKind = "InlineSnippet" | "WorkspacePath";
        export type ScriptExecutionStatus =
          | "Succeeded"
          | "ReferenceResolutionFailed"
          | "CompilationFailed"
          | "RuntimeFailed"
          | "Rejected";
        export type ScriptDiagnosticSeverity = "Info" | "Warning" | "Error";

        export interface ExecuteRevitScriptRequest {
          scriptContent?: string;
          sourceKind?: ScriptExecutionSourceKind;
          sourcePath?: string;
          workspaceKey?: string;
          sourceName?: string;
        }

        export interface ScriptDiagnostic {
          stage: string;
          severity: ScriptDiagnosticSeverity;
          message: string;
          source?: string;
        }

        export interface ExecuteRevitScriptData {
          status: ScriptExecutionStatus;
          output: string;
          diagnostics: ScriptDiagnostic[];
          revitVersion: string;
          targetFramework: string;
          containerTypeName?: string;
          executionId: string;
        }

        export interface HostProblemDetails {
          type?: string;
          title?: string;
          status?: number;
          detail?: string;
          instance?: string;
          [key: string]: unknown;
        }

        export interface PeHostClientOptions {
          baseUrl: string;
          fetch?: typeof fetch;
        }

        export class PeHostClientError extends Error {
          constructor(
            message: string,
            readonly status: number,
            readonly problem?: HostProblemDetails,
          ) {
            super(message);
            this.name = "PeHostClientError";
          }
        }

        export class PeHostClient {
          readonly host: HostClient;
          readonly scripting: ScriptingClient;

          constructor(private readonly options: PeHostClientOptions) {
            this.host = new HostClient(options);
            this.scripting = new ScriptingClient(options);
          }
        }

        export class HostClient {
          constructor(private readonly options: PeHostClientOptions) {}

          getProbe(): Promise<HostProbeData> {
            return sendJson<Record<string, never>, HostProbeData>(
              this.options,
              hostOperations.getProbe,
              {},
            );
          }

          getSessionSummary(): Promise<HostSessionSummaryData> {
            return sendJson<Record<string, never>, HostSessionSummaryData>(
              this.options,
              hostOperations.getSessionSummary,
              {},
            );
          }

          getLogs(request: HostLogsRequest = {}): Promise<HostLogsData> {
            return sendJson<HostLogsRequest, HostLogsData>(
              this.options,
              hostOperations.getLogs,
              request,
            );
          }
        }

        export class ScriptingClient {
          constructor(private readonly options: PeHostClientOptions) {}

          bootstrapWorkspace(
            request: ScriptWorkspaceBootstrapRequest = {},
          ): Promise<ScriptWorkspaceBootstrapData> {
            return sendJson<ScriptWorkspaceBootstrapRequest, ScriptWorkspaceBootstrapData>(
              this.options,
              scriptingOperations.bootstrapWorkspace,
              request,
            );
          }

          execute(request: ExecuteRevitScriptRequest): Promise<ExecuteRevitScriptData> {
            return sendJson<ExecuteRevitScriptRequest, ExecuteRevitScriptData>(
              this.options,
              scriptingOperations.execute,
              request,
            );
          }
        }

        async function sendJson<TRequest, TResponse>(
          options: PeHostClientOptions,
          operation: HostOperationDefinition,
          request?: TRequest,
        ): Promise<TResponse> {
          const fetchImpl = options.fetch ?? fetch;
          const route = operation.verb === "GET" ? appendQueryString(operation.route, request) : operation.route;
          const response = await fetchImpl(`${trimTrailingSlash(options.baseUrl)}${route}`, {
            method: operation.verb,
            headers: operation.verb === "POST" ? { "Content-Type": "application/json" } : undefined,
            body: operation.verb === "POST" ? JSON.stringify(request ?? {}) : undefined,
          });

          const text = await response.text();
          if (!response.ok) {
            const problem = parseJson<HostProblemDetails>(text);
            throw new PeHostClientError(
              problem?.detail ?? problem?.title ?? (text || `${response.status} ${response.statusText}`),
              response.status,
              problem,
            );
          }

          return text ? JSON.parse(text) as TResponse : undefined as TResponse;
        }

        function appendQueryString<TRequest>(route: string, request?: TRequest): string {
          if (!request)
            return route;

          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(request)) {
            if (value != null)
              params.set(key, String(value));
          }
          const query = params.toString();
          if (!query)
            return route;

          return `${route}${route.includes("?") ? "&" : "?"}${query}`;
        }

        function parseJson<T>(text: string): T | undefined {
          if (!text) return undefined;

          try {
            return JSON.parse(text) as T;
          } catch {
            return undefined;
          }
        }

        function trimTrailingSlash(value: string): string {
          return value.endsWith("/") ? value.slice(0, -1) : value;
        }
        """;

    private static string RenderTypeScriptOperationGroup(
        string exportName,
        IReadOnlyList<GeneratedHostClientOperation> operations
    ) {
        var builder = new StringBuilder();
        _ = builder.AppendLine($"export const {exportName} = {{");
        foreach (var operation in operations) {
            _ = builder.AppendLine($"  {operation.MethodName}: {{");
            _ = builder.AppendLine($"    key: \"{operation.Definition.Key}\",");
            _ = builder.AppendLine($"    verb: \"{ToTypeScriptHttpVerb(operation.Definition.Verb)}\",");
            _ = builder.AppendLine($"    route: \"{operation.Definition.Route}\",");
            _ = builder.AppendLine($"    executionMode: \"{operation.Definition.ExecutionMode}\",");
            _ = builder.AppendLine("  },");
        }

        _ = builder.Append("} as const satisfies Record<string, HostOperationDefinition>;");
        return builder.ToString();
    }

    private static void ValidatePeaClientOperations() {
        var generatedKeys = HostClientOperations
            .Concat(ScriptingClientOperations)
            .Select(operation => operation.Definition.Key)
            .ToHashSet(StringComparer.Ordinal);
        var catalogKeys = HostOperationsCatalog.PeaClientSlice
            .Select(definition => definition.Key)
            .ToHashSet(StringComparer.Ordinal);

        var missingFromCatalog = generatedKeys.Except(catalogKeys, StringComparer.Ordinal).ToList();
        if (missingFromCatalog.Count != 0)
            throw new InvalidOperationException(
                $"Generated pea host client contains operations missing from HostOperationsCatalog.PeaClientSlice: {string.Join(", ", missingFromCatalog)}"
            );

        var missingFromGenerator = catalogKeys.Except(generatedKeys, StringComparer.Ordinal).ToList();
        if (missingFromGenerator.Count != 0)
            throw new InvalidOperationException(
                $"HostOperationsCatalog.PeaClientSlice contains operations missing from the generator: {string.Join(", ", missingFromGenerator)}"
            );
    }

    private static string ToTypeScriptHttpVerb(HostHttpVerb verb) => verb switch {
        HostHttpVerb.Get => "GET",
        HostHttpVerb.Post => "POST",
        _ => throw new InvalidOperationException($"Unsupported host operation HTTP verb '{verb}'.")
    };

    private sealed record GeneratedHostClientOperation(string MethodName, HostOperationDefinition Definition);

    private sealed record GeneratedPeaClientFile(string Path, string Content);

    private sealed record PeaHostClientSyncOptions(bool Check) {
        public static PeaHostClientSyncOptions Parse(IReadOnlyList<string> args) {
            var check = false;
            foreach (var arg in args) {
                switch (arg) {
                case "--check":
                    check = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown sync-pea-host-client option '{arg}'. Supported options: --check.");
                }
            }

            return new PeaHostClientSyncOptions(check);
        }
    }
}
