// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from HostOperationsCatalog.PublicHttp.
// Maps each public operation key to its generated request/response zod schemas
// so callers infer types from the key alone — no hand-passed schema argument.

import type { z } from "zod";
import type { HostOperationKey } from "../contracts/host-operations.generated.js";
import * as schemas from "./host-zod.generated.js";

export interface HostOperationSchemaEntry {
  request?: z.ZodType;
  response?: z.ZodType;
}

export const hostOperationSchemas = {
  "aps.auth.login": {
    request: schemas.apsTokenRequestSchema,
    response: schemas.apsPersistedTokenStatusSchema,
  },
  "aps.auth.logout": { response: schemas.apsLogoutResultSchema },
  "aps.auth.status": {
    request: schemas.apsTokenRequestSchema,
    response: schemas.apsPersistedTokenStatusSchema,
  },
  "aps.auth.token": {
    request: schemas.apsTokenRequestSchema,
    response: schemas.apsTokenResultSchema,
  },
  "host.logs": { request: schemas.hostLogsRequestSchema, response: schemas.hostLogsDataSchema },
  "revit.apply.document.open": {
    request: schemas.openRevitDocumentRequestSchema,
    response: schemas.openRevitDocumentDataSchema,
  },
  "revit.catalog.concept-evidence": {
    request: schemas.conceptEvidenceRequestSchema,
    response: schemas.conceptEvidenceDataSchema,
  },
  "revit.catalog.electrical-circuits": {
    request: schemas.electricalCircuitsCatalogRequestSchema,
    response: schemas.electricalCircuitsCatalogDataSchema,
  },
  "revit.catalog.electrical-load-classifications": {
    request: schemas.electricalLoadClassificationsCatalogRequestSchema,
    response: schemas.electricalLoadClassificationsCatalogDataSchema,
  },
  "revit.catalog.electrical-panels": {
    request: schemas.electricalPanelsCatalogRequestSchema,
    response: schemas.electricalPanelsCatalogDataSchema,
  },
  "revit.catalog.loaded-families": {
    request: schemas.loadedFamiliesCatalogRequestSchema,
    response: schemas.loadedFamiliesCatalogDataSchema,
  },
  "revit.catalog.loaded-families.filter-field-options": {
    request: schemas.loadedFamiliesFilterFieldOptionsRequestSchema,
    response: schemas.fieldOptionsDataSchema,
  },
  "revit.catalog.loaded-families.filter-schema": { response: schemas.schemaDataSchema },
  "revit.catalog.parameter-bindings": {
    request: schemas.projectParameterBindingsRequestSchema,
    response: schemas.projectParameterBindingsDataSchema,
  },
  "revit.catalog.parameter-evidence": {
    request: schemas.parameterEvidenceRequestSchema,
    response: schemas.parameterEvidenceDataSchema,
  },
  "revit.catalog.project-browser": {
    request: schemas.projectBrowserRequestSchema,
    response: schemas.projectBrowserDataSchema,
  },
  "revit.catalog.project-index": {
    request: schemas.projectIndexRequestSchema,
    response: schemas.projectIndexDataSchema,
  },
  "revit.catalog.recent-documents": {
    request: schemas.revitRecentDocumentsRequestSchema,
    response: schemas.revitRecentDocumentsDataSchema,
  },
  "revit.catalog.schedules": {
    request: schemas.scheduleCatalogRequestSchema,
    response: schemas.scheduleCatalogDataSchema,
  },
  "revit.context.document-session": { response: schemas.revitDocumentSessionContextDataSchema },
  "revit.context.summary": { response: schemas.revitAgentContextSummaryDataSchema },
  "revit.context.view-rendering-state": {
    request: schemas.revitAgentViewRenderingStateRequestSchema,
    response: schemas.revitAgentViewRenderingStateDataSchema,
  },
  "revit.context.visible-summary": {
    request: schemas.revitAgentVisibleContextRequestSchema,
    response: schemas.revitAgentVisibleContextDataSchema,
  },
  "revit.detail.electrical-panel-schedules": {
    request: schemas.electricalPanelSchedulesQueryRequestSchema,
    response: schemas.electricalPanelSchedulesQueryDataSchema,
  },
  "revit.detail.elements": {
    request: schemas.elementContextQueryRequestSchema,
    response: schemas.elementContextQueryDataSchema,
  },
  "revit.detail.schedules": {
    request: schemas.scheduleQueryRequestSchema,
    response: schemas.scheduleQueryDataSchema,
  },
  "revit.detail.sheets": {
    request: schemas.sheetDetailRequestSchema,
    response: schemas.sheetDetailDataSchema,
  },
  "revit.matrix.loaded-families": {
    request: schemas.loadedFamiliesMatrixRequestSchema,
    response: schemas.loadedFamiliesMatrixDataSchema,
  },
  "revit.matrix.parameter-coverage": {
    request: schemas.parameterCoverageRequestSchema,
    response: schemas.parameterCoverageDataSchema,
  },
  "revit.matrix.schedule-coverage": {
    request: schemas.scheduleCoverageRequestSchema,
    response: schemas.scheduleCoverageDataSchema,
  },
  "revit.matrix.schedule-profiles": {
    request: schemas.scheduleProfilesQueryRequestSchema,
    response: schemas.scheduleProfilesQueryDataSchema,
  },
  "revit.resolve.references": {
    request: schemas.revitAgentContextResolveRequestSchema,
    response: schemas.revitAgentContextResolveDataSchema,
  },
  "scripting.execute": {
    request: schemas.executeRevitScriptRequestSchema,
    response: schemas.executeRevitScriptDataSchema,
  },
  "scripting.pod.export": {
    request: schemas.scriptPodExportRequestSchema,
    response: schemas.scriptPodExportDataSchema,
  },
  "scripting.pod.import": {
    request: schemas.scriptPodImportRequestSchema,
    response: schemas.scriptPodImportDataSchema,
  },
  "scripting.workspace.bootstrap": {
    request: schemas.scriptWorkspaceBootstrapRequestSchema,
    response: schemas.scriptWorkspaceBootstrapDataSchema,
  },
  "settings.document.open": {
    request: schemas.openSettingsDocumentRequestSchema,
    response: schemas.settingsDocumentSnapshotSchema,
  },
  "settings.document.save": {
    request: schemas.saveSettingsDocumentRequestSchema,
    response: schemas.saveSettingsDocumentResultSchema,
  },
  "settings.document.validate": {
    request: schemas.validateSettingsDocumentRequestSchema,
    response: schemas.settingsValidationResultSchema,
  },
  "settings.field-options": {
    request: schemas.fieldOptionsRequestSchema,
    response: schemas.fieldOptionsDataSchema,
  },
  "settings.host-probe": { response: schemas.hostProbeDataSchema },
  "settings.parameter-catalog": {
    request: schemas.parameterCatalogRequestSchema,
    response: schemas.parameterCatalogDataSchema,
  },
  "settings.schema": { request: schemas.schemaRequestSchema, response: schemas.schemaDataSchema },
  "settings.session-summary": { response: schemas.hostSessionSummaryDataSchema },
  "settings.tree": {
    request: schemas.settingsTreeRequestSchema,
    response: schemas.settingsDiscoveryResultSchema,
  },
  "settings.workspaces": {
    request: schemas.getSettingsWorkspacesRequestSchema,
    response: schemas.settingsWorkspacesDataSchema,
  },
} as const satisfies Record<HostOperationKey, HostOperationSchemaEntry>;
