using System.Collections;
using System.Reflection;
using System.Text;

namespace Pe.Dev.Cli.Codegen;

internal static class HostEffectSchemaProjection {
    public static string Generate(IReadOnlyCollection<Type> exportedTypes) {
        var enums = exportedTypes.Where(type => type.IsEnum)
            .OrderBy(type => type.Name, StringComparer.Ordinal)
            .ToArray();
        var objects = exportedTypes.Where(type => !type.IsEnum).ToArray();
        var builder = new StringBuilder();
        _ = builder.AppendLine("// <auto-generated />");
        _ = builder.AppendLine("// Generated by `pe-dev codegen sync --target host-contracts` from the exported host types.");
        _ = builder.AppendLine("// Effect Schema projection for TS host runtime validation.");
        _ = builder.AppendLine();
        _ = builder.AppendLine("import { Schema } from \"effect\";");
        _ = builder.AppendLine();

        foreach (var enumType in enums) {
            _ = builder.Append(RenderEnumValueObject(enumType));
            _ = builder.AppendLine($"export const {SchemaName(enumType.Name)} = Schema.Literals([{RenderEnumLiterals(enumType)}]);");
            _ = builder.AppendLine($"export type {enumType.Name} = Schema.Schema.Type<typeof {SchemaName(enumType.Name)}>;");
            _ = builder.AppendLine();
        }

        foreach (var type in objects.OrderBy(type => type.Name, StringComparer.Ordinal)) {
            _ = builder.Append(RenderObjectSchema(type));
        }

        foreach (var type in objects.OrderBy(type => type.Name, StringComparer.Ordinal)) {
            _ = builder.AppendLine($"export type {type.Name} = Schema.Schema.Type<typeof {SchemaName(type.Name)}>;");
        }

        return builder.ToString();
    }

    private static string RenderObjectSchema(Type type) {
        var schemaName = SchemaName(type.Name);
        var nullability = new NullabilityInfoContext();
        var defaultInstance = type.GetConstructor(Type.EmptyTypes) == null ? null : SafeCreate(type);

        var builder = new StringBuilder();
        _ = builder.AppendLine($"export const {schemaName} = Schema.suspend(");
        _ = builder.AppendLine("  () =>");
        _ = builder.AppendLine("  Schema.Struct({");
        foreach (var property in type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetIndexParameters().Length == 0)
            .OrderBy(property => property.Name, StringComparer.Ordinal)) {
            var info = nullability.Create(property);
            var expression = RenderProperty(property, info, defaultInstance);
            _ = builder.AppendLine($"    {ToCamelCase(property.Name)}: {expression},");
        }
        _ = builder.AppendLine("  }),");
        _ = builder.AppendLine(");");
        _ = builder.AppendLine();
        return builder.ToString();
    }

    private static string RenderProperty(PropertyInfo property, NullabilityInfo info, object? defaultInstance) {
        var expression = RenderType(property.PropertyType, info);
        if (IsNullableProperty(property, info))
            return $"Schema.optional(Schema.NullOr({expression}))";

        if (IsDefaultOptionalProperty(property, defaultInstance))
            return $"Schema.optional({expression})";

        return expression;
    }

    private static bool IsOptionalProperty(PropertyInfo property, NullabilityInfo info, object? defaultInstance) =>
        IsNullableProperty(property, info) || IsDefaultOptionalProperty(property, defaultInstance);

    private static bool IsNullableProperty(PropertyInfo property, NullabilityInfo info) {
        var nullableValueType = Nullable.GetUnderlyingType(property.PropertyType) != null;
        var nullableRef = !property.PropertyType.IsValueType && info.ReadState == NullabilityState.Nullable;
        return nullableValueType || nullableRef;
    }

    private static bool IsDefaultOptionalProperty(PropertyInfo property, object? defaultInstance) =>
        defaultInstance != null && property.GetValue(defaultInstance) != null;

    private static string RenderType(Type type, NullabilityInfo? info) {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying != null)
            return RenderType(underlying, null);

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return "Schema.String";
        if (type == typeof(bool))
            return "Schema.Boolean";
        if (type.IsEnum)
            return SchemaName(type.Name);
        if (IsNumeric(type))
            return "Schema.Number";

        if (TryGetDictionaryValueType(type, out var valueType, out var valueIndex)) {
            var valueInfo = info != null && info.GenericTypeArguments.Length > valueIndex
                ? info.GenericTypeArguments[valueIndex]
                : null;
            var valueExpression = RenderType(valueType, valueInfo);
            if (valueInfo?.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(valueType) != null)
                valueExpression = $"Schema.NullOr({valueExpression})";
            return $"Schema.Record(Schema.String, {valueExpression})";
        }

        if (TryGetEnumerableElementType(type, out var elementType)) {
            var elementInfo = info != null && info.GenericTypeArguments.Length > 0 ? info.GenericTypeArguments[0] : null;
            var elementExpression = RenderType(elementType, elementInfo);
            if (elementInfo?.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(elementType) != null)
                elementExpression = $"Schema.NullOr({elementExpression})";
            return $"Schema.Array({elementExpression})";
        }

        if (LooksLikeExportedObject(type))
            return $"Schema.suspend(() => {SchemaName(type.Name)})";

        return "Schema.Unknown";
    }

    private static bool TryGetDictionaryValueType(Type type, out Type valueType, out int valueIndex) {
        foreach (var candidate in type.IsGenericType ? new[] { type }.Concat(type.GetInterfaces()) : type.GetInterfaces()) {
            if (candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>)) {
                valueType = candidate.GetGenericArguments()[1];
                valueIndex = 1;
                return true;
            }
            if (candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)) {
                valueType = candidate.GetGenericArguments()[1];
                valueIndex = 1;
                return true;
            }
        }

        valueType = typeof(object);
        valueIndex = 0;
        return false;
    }

    private static bool TryGetEnumerableElementType(Type type, out Type elementType) {
        if (type == typeof(string)) {
            elementType = typeof(char);
            return false;
        }

        if (type.IsArray) {
            elementType = type.GetElementType()!;
            return true;
        }

        var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
            ? type
            : type.GetInterfaces().FirstOrDefault(candidate =>
                candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        if (enumerable != null) {
            elementType = enumerable.GetGenericArguments()[0];
            return true;
        }

        elementType = typeof(object);
        return false;
    }

    private static bool IsNumeric(Type type) {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;
        return underlying == typeof(byte)
               || underlying == typeof(sbyte)
               || underlying == typeof(short)
               || underlying == typeof(ushort)
               || underlying == typeof(int)
               || underlying == typeof(uint)
               || underlying == typeof(long)
               || underlying == typeof(ulong)
               || underlying == typeof(float)
               || underlying == typeof(double)
               || underlying == typeof(decimal);
    }

    private static bool LooksLikeExportedObject(Type type) =>
        type is { IsClass: true } or { IsValueType: true, IsPrimitive: false, IsEnum: false }
        && type != typeof(string)
        && !type.IsGenericType;

    private static object? SafeCreate(Type type) {
        try {
            return Activator.CreateInstance(type);
        } catch {
            return null;
        }
    }

    private static string RenderEnumLiterals(Type enumType) =>
        string.Join(", ", Enum.GetNames(enumType).Select(ToJsonString));

    private static string RenderEnumValueObject(Type enumType) {
        var builder = new StringBuilder();
        _ = builder.AppendLine($"export const {enumType.Name} = {{");
        foreach (var name in Enum.GetNames(enumType))
            _ = builder.AppendLine($"  {name}: {ToJsonString(name)},");
        _ = builder.AppendLine("} as const;");
        return builder.ToString();
    }

    private static string SchemaName(string typeName) => $"{ToCamelCase(typeName)}Schema";

    private static string ToCamelCase(string value) => string.IsNullOrEmpty(value)
        ? value
        : char.ToLowerInvariant(value[0]) + value[1..];

    private static string ToJsonString(string value) => System.Text.Json.JsonSerializer.Serialize(value);
}
