using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Reflection;
using System.Text;

namespace Pe.Dev.Cli.Codegen;

/// <summary>
/// Emits zod schemas for the exported host-contract types, reflected straight
/// from the C# types. This sees nullability that TypeGen discards — notably
/// <c>Dictionary&lt;string, string?&gt;</c> value-nullability, which the wire
/// actually uses but the generated TS interface renders as non-null. The web
/// app infers its boundary types from these schemas (<c>z.infer</c>), so a C#
/// contract change moves both the schema and the inferred type in lockstep.
/// </summary>
internal static class HostZodProjection {
    public static string Generate(IReadOnlyCollection<Type> exportedTypes) {
        var enums = exportedTypes.Where(type => type.IsEnum)
            .OrderBy(type => type.Name, StringComparer.Ordinal)
            .ToArray();
        var objects = exportedTypes.Where(type => !type.IsEnum)
            .ToArray();
        var objectNames = objects.Select(type => type.Name).ToHashSet(StringComparer.Ordinal);

        var builder = new StringBuilder();
        _ = builder.AppendLine("// <auto-generated />");
        _ = builder.AppendLine("// Generated by `pe-dev codegen sync --target host-contracts` from the exported host types.");
        _ = builder.AppendLine("// Schemas are reflected from C#; infer boundary types with `z.infer<typeof xSchema>`.");
        _ = builder.AppendLine();
        _ = builder.AppendLine("import { z } from \"zod\";");
        // Enums bind to the generated TS enums so inferred types are the nominal
        // enums (not loose string unions) — value usage and parsing stay in sync.
        if (enums.Length != 0) {
            var names = string.Join(", ", enums.Select(type => type.Name));
            _ = builder.AppendLine($"import {{ {names} }} from \"../types/index.js\";");
        }
        _ = builder.AppendLine();

        foreach (var enumType in enums)
            _ = builder.AppendLine($"export const {SchemaName(enumType.Name)} = z.enum({enumType.Name});");
        if (enums.Length != 0)
            _ = builder.AppendLine();

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in TopologicalOrder(objects, objectNames)) {
            _ = builder.Append(RenderObjectSchema(type, objectNames, emitted));
            _ = emitted.Add(type.Name);
        }

        return builder.ToString();
    }

    private static string RenderObjectSchema(Type type, IReadOnlySet<string> objectNames, IReadOnlySet<string> emitted) {
        var schemaName = SchemaName(type.Name);
        var nullability = new NullabilityInfoContext();
        var defaultInstance = type.GetConstructor(Type.EmptyTypes) == null ? null : SafeCreate(type);

        var builder = new StringBuilder();
        _ = builder.AppendLine($"export const {schemaName} = z");
        _ = builder.AppendLine("  .object({");
        foreach (var property in type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetIndexParameters().Length == 0)
            .OrderBy(property => property.Name, StringComparer.Ordinal)) {
            var info = nullability.Create(property);
            var expression = RenderProperty(property, info, defaultInstance);
            var camel = ToCamelCase(property.Name);
            // Recursive / forward references (e.g. SettingsDirectoryNode.directories)
            // can't reference a const inside its own initializer — emit a zod v4
            // getter so the reference is resolved lazily.
            if (ReferencesUnemitted(property.PropertyType, type.Name, objectNames, emitted))
                _ = builder.AppendLine($"    get {camel}() {{ return {expression}; }},");
            else
                _ = builder.AppendLine($"    {camel}: {expression},");
        }
        // strip-by-default tolerates host-added keys; that is the intended boundary stance.
        _ = builder.AppendLine("  });");
        _ = builder.AppendLine($"export type {type.Name} = z.infer<typeof {schemaName}>;");
        _ = builder.AppendLine();
        return builder.ToString();
    }

    private static bool ReferencesUnemitted(
        Type propertyType,
        string currentTypeName,
        IReadOnlySet<string> objectNames,
        IReadOnlySet<string> emitted
    ) => LeafTypes(propertyType)
        .Where(leaf => objectNames.Contains(leaf.Name))
        .Any(leaf => leaf.Name == currentTypeName || !emitted.Contains(leaf.Name));

    private static string RenderProperty(PropertyInfo property, NullabilityInfo info, object? defaultInstance) {
        var underlying = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
        var baseExpression = RenderType(property.PropertyType, info) + RenderRefinements(property, underlying);

        // `[Required]` is the validation source of truth for presence: the field
        // must be present and non-null regardless of CLR nullability/defaults.
        if (property.GetCustomAttribute<RequiredAttribute>() != null)
            return baseExpression;

        var nullableValueType = Nullable.GetUnderlyingType(property.PropertyType) != null;
        var nullableRef = !property.PropertyType.IsValueType && info.ReadState == NullabilityState.Nullable;
        if (nullableValueType || nullableRef)
            return $"{baseExpression}.nullish()";

        // Records expose defaults that let the host omit the field; optional, non-null.
        if (defaultInstance != null && property.GetValue(defaultInstance) != null)
            return $"{baseExpression}.optional()";

        return baseExpression;
    }

    // DataAnnotations are the single validation source of truth: NJsonSchema reads
    // them for the settings JSON Schema; this reads the same attributes for zod.
    private static string RenderRefinements(PropertyInfo property, Type underlying) {
        var isString = underlying == typeof(string);
        var isNumber = IsNumeric(underlying);
        var isCollection = !isString && TryGetEnumerableElementType(underlying, out _);
        var sb = new StringBuilder();

        var range = property.GetCustomAttribute<RangeAttribute>();
        if (range != null && isNumber) {
            if (TryFormatNumber(range.Minimum, out var min))
                _ = sb.Append($".min({min})");
            if (TryFormatNumber(range.Maximum, out var max))
                _ = sb.Append($".max({max})");
        }

        var stringLength = property.GetCustomAttribute<StringLengthAttribute>();
        if (stringLength != null && isString) {
            if (stringLength.MinimumLength > 0)
                _ = sb.Append($".min({stringLength.MinimumLength})");
            _ = sb.Append($".max({stringLength.MaximumLength})");
        }

        var minLength = property.GetCustomAttribute<MinLengthAttribute>();
        if (minLength != null && (isString || isCollection))
            _ = sb.Append($".min({minLength.Length})");
        var maxLength = property.GetCustomAttribute<MaxLengthAttribute>();
        if (maxLength != null && (isString || isCollection))
            _ = sb.Append($".max({maxLength.Length})");

        if (isString) {
            var regex = property.GetCustomAttribute<RegularExpressionAttribute>();
            if (regex != null)
                _ = sb.Append($".regex(/{EscapeRegexLiteral(regex.Pattern)}/)");
            if (property.GetCustomAttribute<EmailAddressAttribute>() != null)
                _ = sb.Append(".email()");
            if (property.GetCustomAttribute<UrlAttribute>() != null)
                _ = sb.Append(".url()");
        }

        return sb.ToString();
    }

    private static bool TryFormatNumber(object? value, out string formatted) {
        formatted = "";
        if (value == null)
            return false;
        try {
            var number = Convert.ToDouble(value, CultureInfo.InvariantCulture);
            if (double.IsInfinity(number) || double.IsNaN(number))
                return false;
            formatted = number.ToString("0.################", CultureInfo.InvariantCulture);
            return true;
        } catch {
            return false;
        }
    }

    // Render a .NET regex pattern as a JS regex literal body. Common syntax
    // (\d, [A-Z], ^$, quantifiers) is shared and backslashes pass through; only a
    // literal `/` needs escaping so it doesn't close the literal.
    private static string EscapeRegexLiteral(string pattern) => pattern.Replace("/", "\\/");

    private static string RenderType(Type type, NullabilityInfo? info) {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying != null)
            return RenderType(underlying, null);

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return "z.string()";
        if (type == typeof(bool))
            return "z.boolean()";
        if (type.IsEnum)
            return SchemaName(type.Name);
        if (IsNumeric(type))
            return "z.number()";

        if (TryGetDictionaryValueType(type, out var valueType, out var valueIndex)) {
            var valueInfo = info != null && info.GenericTypeArguments.Length > valueIndex
                ? info.GenericTypeArguments[valueIndex]
                : null;
            var valueExpression = RenderType(valueType, valueInfo);
            if (valueInfo?.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(valueType) != null)
                valueExpression = $"{valueExpression}.nullable()";
            return $"z.record(z.string(), {valueExpression})";
        }

        if (TryGetEnumerableElementType(type, out var elementType)) {
            var elementInfo = info != null && info.GenericTypeArguments.Length > 0 ? info.GenericTypeArguments[0] : null;
            var elementExpression = RenderType(elementType, elementInfo);
            if (elementInfo?.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(elementType) != null)
                elementExpression = $"{elementExpression}.nullable()";
            return $"z.array({elementExpression})";
        }

        // Exported object type → reference its schema. Unknown leaf → tolerate.
        if (LooksLikeExportedObject(type))
            return SchemaName(type.Name);

        return "z.unknown()";
    }

    private static bool LooksLikeExportedObject(Type type) =>
        type is { IsClass: true } or { IsValueType: true, IsPrimitive: false, IsEnum: false }
        && type != typeof(string)
        && !type.IsGenericType;

    private static IEnumerable<Type> TopologicalOrder(IReadOnlyList<Type> objects, IReadOnlySet<string> objectNames) {
        var byName = objects.ToDictionary(type => type.Name, StringComparer.Ordinal);
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var visiting = new HashSet<string>(StringComparer.Ordinal);
        var ordered = new List<Type>();

        void Visit(Type type) {
            if (emitted.Contains(type.Name) || !visiting.Add(type.Name))
                return;

            foreach (var dependencyName in ReferencedObjectNames(type, objectNames).OrderBy(name => name, StringComparer.Ordinal))
                if (byName.TryGetValue(dependencyName, out var dependency))
                    Visit(dependency);

            _ = visiting.Remove(type.Name);
            if (emitted.Add(type.Name))
                ordered.Add(type);
        }

        foreach (var type in objects.OrderBy(type => type.Name, StringComparer.Ordinal))
            Visit(type);

        return ordered;
    }

    private static IEnumerable<string> ReferencedObjectNames(Type type, IReadOnlySet<string> objectNames) {
        foreach (var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public)) {
            foreach (var referenced in LeafTypes(property.PropertyType))
                if (objectNames.Contains(referenced.Name))
                    yield return referenced.Name;
        }
    }

    private static IEnumerable<Type> LeafTypes(Type type) {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying != null) {
            foreach (var leaf in LeafTypes(underlying))
                yield return leaf;
            yield break;
        }

        if (TryGetDictionaryValueType(type, out var valueType, out _)) {
            foreach (var leaf in LeafTypes(valueType))
                yield return leaf;
            yield break;
        }

        if (TryGetEnumerableElementType(type, out var elementType)) {
            foreach (var leaf in LeafTypes(elementType))
                yield return leaf;
            yield break;
        }

        yield return type;
    }

    private static bool IsNumeric(Type type) => type == typeof(byte) || type == typeof(sbyte)
        || type == typeof(short) || type == typeof(ushort) || type == typeof(int) || type == typeof(uint)
        || type == typeof(long) || type == typeof(ulong) || type == typeof(float) || type == typeof(double)
        || type == typeof(decimal);

    private static bool TryGetEnumerableElementType(Type type, out Type elementType) {
        elementType = typeof(object);
        if (type == typeof(string) || typeof(IDictionary).IsAssignableFrom(type))
            return false;

        var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
            ? type
            : type.GetInterfaces().FirstOrDefault(candidate =>
                candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        if (enumerable == null)
            return false;

        elementType = enumerable.GetGenericArguments()[0];
        return true;
    }

    private static bool TryGetDictionaryValueType(Type type, out Type valueType, out int valueIndex) {
        valueType = typeof(object);
        valueIndex = 1;
        var dictionary = type.GetInterfaces().Append(type).FirstOrDefault(candidate =>
            candidate.IsGenericType
            && (candidate.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)
                || candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>)));
        if (dictionary == null)
            return false;

        valueType = dictionary.GetGenericArguments()[1];
        return true;
    }

    private static object? SafeCreate(Type type) {
        try {
            return Activator.CreateInstance(type);
        } catch {
            return null;
        }
    }

    private static string SchemaName(string typeName) => $"{ToCamelCase(typeName)}Schema";

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value[1..];
}
