using Pe.Dev.RevitAutomation;
using Pe.Shared.HostContracts.Operations;
using System.Text;

namespace Pe.Dev.Cli;

internal static class HostTypeScriptClientProjection {
    public static async Task<int> RunAsync(
        IReadOnlyList<string> forwardedArguments,
        string? repoRootOverride,
        CancellationToken cancellationToken
    ) {
        HostTypeScriptClientOptions options;
        string repoRoot;
        try {
            options = HostTypeScriptClientOptions.Parse(forwardedArguments);
            repoRoot = RepoRootResolver.Resolve(repoRootOverride);
        } catch (Exception ex) {
            Console.Error.WriteLine(ex.Message);
            return 10;
        }

        var buildExit = await HostTypeGenerationModelProvider.EnsureFreshBuildAsync(repoRoot, cancellationToken);
        if (buildExit != 0)
            return buildExit;

        HostTypeGenerationModelProvider.GeneratedHostTypeModel generatedHostTypeModel;
        try {
            generatedHostTypeModel = HostTypeGenerationModelProvider.Load(repoRoot);
        } catch (Exception ex) {
            Console.Error.WriteLine($"Host TypeScript client generation failed: {ex.Message}");
            return 1;
        }

        GeneratedProjectionFile[] generatedFiles;
        try {
            generatedFiles = GenerateFiles(repoRoot, generatedHostTypeModel);
        } catch (Exception ex) {
            Console.Error.WriteLine($"Host TypeScript client generation failed: {ex.Message}");
            return 1;
        }

        if (options.Check)
            return await CheckAsync(repoRoot, generatedFiles, cancellationToken);

        foreach (var extraFile in EnumerateCommittedGeneratedFiles(repoRoot).Where(path => generatedFiles.All(file => !string.Equals(file.Path, path, StringComparison.OrdinalIgnoreCase)))) {
            File.Delete(extraFile);
            Console.WriteLine($"Deleted {Path.GetRelativePath(repoRoot, extraFile)}");
        }

        foreach (var generatedFile in generatedFiles) {
            Directory.CreateDirectory(Path.GetDirectoryName(generatedFile.Path)!);
            await File.WriteAllTextAsync(generatedFile.Path, generatedFile.Content, cancellationToken);
            Console.WriteLine($"Generated {Path.GetRelativePath(repoRoot, generatedFile.Path)}");
        }

        return 0;
    }

    private static async Task<int> CheckAsync(
        string repoRoot,
        IReadOnlyList<GeneratedProjectionFile> generatedFiles,
        CancellationToken cancellationToken
    ) {
        var staleFiles = new List<string>();
        var expectedPaths = generatedFiles.Select(file => Path.GetFullPath(file.Path)).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var generatedFile in generatedFiles) {
            var relativePath = Path.GetRelativePath(repoRoot, generatedFile.Path);
            if (!File.Exists(generatedFile.Path)) {
                staleFiles.Add($"{relativePath} (missing)");
                continue;
            }

            var existingContent = await File.ReadAllTextAsync(generatedFile.Path, cancellationToken);
            if (!string.Equals(existingContent, generatedFile.Content, StringComparison.Ordinal))
                staleFiles.Add(relativePath);
        }

        foreach (var extraFile in EnumerateCommittedGeneratedFiles(repoRoot).Where(path => !expectedPaths.Contains(path)))
            staleFiles.Add($"{Path.GetRelativePath(repoRoot, extraFile)} (extra)");

        if (staleFiles.Count == 0) {
            Console.WriteLine("Generated Host TypeScript client is current.");
            return 0;
        }

        Console.Error.WriteLine("Generated Host TypeScript client is stale:");
        foreach (var staleFile in staleFiles)
            Console.Error.WriteLine($"  {staleFile}");
        Console.Error.WriteLine("Run `pe-dev codegen sync --target host-client` to update it.");
        return 1;
    }

    private static GeneratedProjectionFile[] GenerateFiles(
        string repoRoot,
        HostTypeGenerationModelProvider.GeneratedHostTypeModel generatedHostTypeModel
    ) {
        ValidateProjectedTypeSymbols(generatedHostTypeModel.ExportedTypeNames);
        var generatedPath = Path.Combine(repoRoot, "source", "pea", "app", "generated", "host-client.generated.ts");
        return [
            new GeneratedProjectionFile(generatedPath, GenerateTypeScriptClient(generatedHostTypeModel.ExportedTypeNames))
        ];
    }

    private static string GenerateTypeScriptClient(IReadOnlyDictionary<string, string> exportedTypeNames) => $$"""
        // <auto-generated />
        // Generated by `pe-dev codegen sync --target host-client` from HostOperationsCatalog.TypeScriptClient.

        import { sendJson, type HostOperationDefinition, type PeHostClientOptions } from "../host-client-runtime.js";
        import type {
        {{RenderTypeScriptImports(exportedTypeNames)}}
        } from "./host-types/index.js";

        {{RenderTypeScriptOperationGroups()}}
        """;

    private static string RenderTypeScriptImports(IReadOnlyDictionary<string, string> exportedTypeNames) {
        var importedTypes = HostOperationsCatalog.TypeScriptClient.Groups
            .SelectMany(group => group.Operations)
            .SelectMany(operation => new[] {
                ResolveTypeScriptTypeName(operation.Definition.RequestType, exportedTypeNames),
                ResolveTypeScriptTypeName(operation.Definition.ResponseType, exportedTypeNames)
            })
            .Where(typeName => typeName != null)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(typeName => typeName, StringComparer.Ordinal)
            .ToArray();
        return string.Join(
            Environment.NewLine,
            importedTypes.Select(typeName => $"  {typeName},")
        );
    }

    private static string RenderTypeScriptOperationGroups() => string.Join(
        $"{Environment.NewLine}{Environment.NewLine}",
        HostOperationsCatalog.TypeScriptClient.Groups.Select(RenderTypeScriptGroup)
    );

    private static string RenderTypeScriptGroup(HostTypeScriptClientGroup group) {
        var builder = new StringBuilder();
        var operationsConstantName = $"{group.ClientPropertyName}Operations";
        _ = builder.AppendLine(RenderTypeScriptOperationGroup(operationsConstantName, group.Operations));
        _ = builder.AppendLine();
        _ = builder.AppendLine($"export class {group.ClientClassName} {{");
        _ = builder.AppendLine("  constructor(private readonly options: PeHostClientOptions) {}");
        _ = builder.AppendLine();
        foreach (var operation in group.Operations)
            _ = builder.AppendLine(RenderTypeScriptMethod(group, operation));
        _ = builder.Append("}");
        return builder.ToString();
    }

    private static string RenderTypeScriptOperationGroup(string exportName, IReadOnlyList<HostTypeScriptClientOperation> operations) {
        var builder = new StringBuilder();
        _ = builder.AppendLine($"export const {exportName} = {{");
        foreach (var operation in operations) {
            _ = builder.AppendLine($"  {operation.MethodName}: {{");
            _ = builder.AppendLine($"    key: \"{operation.Definition.Key}\",");
            _ = builder.AppendLine($"    verb: \"{ToTypeScriptHttpVerb(operation.Definition.Verb)}\",");
            _ = builder.AppendLine($"    route: \"{operation.Definition.Route}\",");
            _ = builder.AppendLine($"    executionMode: \"{operation.Definition.ExecutionMode}\",");
            _ = builder.AppendLine("  },");
        }

        _ = builder.Append("} as const satisfies Record<string, HostOperationDefinition>;");
        return builder.ToString();
    }

    private static string RenderTypeScriptMethod(
        HostTypeScriptClientGroup group,
        HostTypeScriptClientOperation operation
    ) {
        var requestTypeName = ResolveTypeScriptTypeName(operation.Definition.RequestType, null);
        var responseTypeName = ResolveTypeScriptTypeName(operation.Definition.ResponseType, null)
            ?? throw new InvalidOperationException($"Operation '{operation.Definition.Key}' is missing a projected response type.");
        var operationsConstantName = $"{group.ClientPropertyName}Operations";
        var builder = new StringBuilder();
        switch (operation.RequestPolicy) {
        case HostClientRequestPolicy.None:
            _ = builder.AppendLine($"  {operation.MethodName}(): Promise<{responseTypeName}> {{");
            _ = builder.AppendLine($"    return sendJson<void, {responseTypeName}>(");
            _ = builder.AppendLine("      this.options,");
            _ = builder.AppendLine($"      {operationsConstantName}.{operation.MethodName},");
            _ = builder.AppendLine("    );");
            _ = builder.Append("  }");
            break;
        case HostClientRequestPolicy.Explicit:
            if (requestTypeName == null)
                throw new InvalidOperationException($"Operation '{operation.Definition.Key}' is missing a projected request type.");
            _ = builder.AppendLine($"  {operation.MethodName}(request: {requestTypeName}): Promise<{responseTypeName}> {{");
            _ = builder.AppendLine($"    return sendJson<{requestTypeName}, {responseTypeName}>(");
            _ = builder.AppendLine("      this.options,");
            _ = builder.AppendLine($"      {operationsConstantName}.{operation.MethodName},");
            _ = builder.AppendLine("      request,");
            _ = builder.AppendLine("    );");
            _ = builder.Append("  }");
            break;
        default:
            throw new InvalidOperationException($"Unsupported request policy '{operation.RequestPolicy}'.");
        }

        return builder.ToString();
    }

    private static void ValidateProjectedTypeSymbols(IReadOnlyDictionary<string, string> exportedTypeNames) {
        var missingTypes = HostOperationsCatalog.TypeScriptClient.Groups
            .SelectMany(group => group.Operations)
            .SelectMany(operation => new[] { operation.Definition.RequestType, operation.Definition.ResponseType })
            .Where(type => type != typeof(NoRequest))
            .Where(type => string.IsNullOrWhiteSpace(type.FullName) || !exportedTypeNames.ContainsKey(type.FullName!))
            .Select(type => type.FullName ?? type.Name)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
        if (missingTypes.Length != 0)
            throw new InvalidOperationException(
                $"TypeScript client projection references types missing from host-types exports: {string.Join(", ", missingTypes)}"
            );
    }

    private static string? ResolveTypeScriptTypeName(
        Type type,
        IReadOnlyDictionary<string, string>? exportedTypeNames
    ) {
        if (type == typeof(NoRequest))
            return null;

        if (exportedTypeNames == null)
            return type.Name;

        if (string.IsNullOrWhiteSpace(type.FullName) || !exportedTypeNames.TryGetValue(type.FullName, out var typeName))
            throw new InvalidOperationException(
                $"Type '{type.FullName ?? type.Name}' is not exported through generated host-types."
            );

        return typeName;
    }

    private static IEnumerable<string> EnumerateCommittedGeneratedFiles(string repoRoot) {
        var generatedDirectory = Path.Combine(repoRoot, "source", "pea", "app", "generated");
        if (!Directory.Exists(generatedDirectory))
            return [];

        return Directory.EnumerateFiles(generatedDirectory, "*.ts", SearchOption.TopDirectoryOnly)
            .Where(path => {
                var fileName = Path.GetFileName(path);
                return string.Equals(fileName, "pe-host-client.ts", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(fileName, "host-client.generated.ts", StringComparison.OrdinalIgnoreCase);
            })
            .Select(Path.GetFullPath);
    }

    private static string ToTypeScriptHttpVerb(HostHttpVerb verb) => verb switch {
        HostHttpVerb.Get => "GET",
        HostHttpVerb.Post => "POST",
        _ => throw new InvalidOperationException($"Unsupported host operation HTTP verb '{verb}'.")
    };

    private sealed record GeneratedProjectionFile(string Path, string Content);

    private sealed record HostTypeScriptClientOptions(bool Check) {
        public static HostTypeScriptClientOptions Parse(IReadOnlyList<string> args) {
            var check = false;
            foreach (var arg in args) {
                switch (arg) {
                case "--check":
                    check = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown host-client codegen option '{arg}'. Supported options: --check.");
                }
            }

            return new HostTypeScriptClientOptions(check);
        }
    }
}
