using System.Reflection;
using System.Text.Json;
using Pe.Shared.Product;

namespace Pe.Dev.Cli.Codegen;

internal static class ProductTypeScriptProjection {
    public static async Task<int> RunAsync(CodegenPaths paths, CancellationToken cancellationToken) {
        var generatedFile = GenerateFile(paths);
        GeneratedProjectionSync.DeleteStaleFiles(
            paths.RepoRoot,
            [generatedFile.Path],
            EnumerateProductGeneratedFiles(paths)
        );

        Directory.CreateDirectory(Path.GetDirectoryName(generatedFile.Path)!);
        await File.WriteAllTextAsync(generatedFile.Path, generatedFile.Content, cancellationToken);
        Console.WriteLine($"Generated {Path.GetRelativePath(paths.RepoRoot, generatedFile.Path)}");
        return 0;
    }

    private static GeneratedProjectionFile GenerateFile(CodegenPaths paths) => new(
        Path.Combine(paths.HostContractsDirectory, "product.generated.ts"),
        NormalizeLineEndings(GenerateTypeScript())
    );

    private static string GenerateTypeScript() => $$"""
        // <auto-generated />
        // Generated by `pe-dev codegen sync --target product` from Pe.Shared.Product.

        {{RenderConstantObject("productIdentity", typeof(ProductIdentity))}}

        {{RenderConstantObject("productPathNames", typeof(ProductPathNames))}}

        {{RenderConstantObject("hostProcessIdentity", typeof(HostProcessIdentity))}}

        {{RenderConstantObject("peaCliIdentity", typeof(PeaCliIdentity))}}

        {{RenderConstantObject("peDevCliIdentity", typeof(PeDevCliIdentity))}}

        {{RenderConstantObject("revitDeploymentIdentity", typeof(RevitDeploymentIdentity))}}

        {{RenderConstantObject("peAppRuntimeDeploymentDescriptor", typeof(PeAppRuntimeDeploymentDescriptor))}}

        {{RenderConstantObject("installerPayloadManifest", typeof(InstallerPayloadManifest))}}

        {{RenderConstantObject("scriptingWorkspaceIdentity", typeof(ScriptingWorkspaceLayout))}}
        """;

    private static string RenderConstantObject(string exportName, Type sourceType) {
        var fields = sourceType
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(field => field.IsLiteral && !field.IsInitOnly)
            .OrderBy(field => field.MetadataToken)
            .ToArray();

        if (fields.Length == 0)
            throw new InvalidOperationException($"Product projection source '{sourceType.FullName}' has no public constants.");

        var lines = fields.Select(field => {
            var value = field.GetRawConstantValue()
                ?? throw new InvalidOperationException($"Product projection constant '{sourceType.FullName}.{field.Name}' is null.");
            return $"  {ToCamelCase(field.Name)}: {Ts(value)},";
        });

        return string.Join(
            "\n",
            new[] { $"export const {exportName} = {{" }
                .Concat(lines)
                .Concat(["} as const;"])
        );
    }

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) || char.IsLower(value[0])
            ? value
            : char.ToLowerInvariant(value[0]) + value[1..];

    private static string Ts(object value) => JsonSerializer.Serialize(value);

    private static string NormalizeLineEndings(string content) {
        var normalized = content.Replace("\r\n", "\n").Replace("\r", "\n");
        return normalized.EndsWith('\n') ? normalized : normalized + "\n";
    }

    private static IEnumerable<string> EnumerateProductGeneratedFiles(CodegenPaths paths) =>
        GeneratedProjectionSync.EnumerateFiles(paths.HostContractsDirectory, "product*.generated.ts", SearchOption.TopDirectoryOnly);

    private sealed record GeneratedProjectionFile(string Path, string Content);
}
