export type AnnotationVariant =
  | "frame"
  | "scroller"
  | "grid"
  | "dial"
  | "dial-strip"
  | "dial-band"
  | "dial-number"
  | "reticle-wick"
  | "reticle-cap"
  | "reticle-focal"
  | "caret"
  | "tail"
  | "chat"
  | "side-pane"
  | "trace-frame"
  | "trace-pin"
  | "inspect"
  | "scrim"
  | "moment"
  | "streaming-caret"
  | "tool-marker"
  | "tool-run"
  | "tool-body"
  | "trace-cell"
  | "cell-head"
  | "cell-title"
  | "cell-meta"
  | "tool-image";

export const annotation = (variant: AnnotationVariant) => ({ "data-annotation": variant }) as const;
