using Pe.Shared.Product;

namespace Pe.Revit.Scripting.Bootstrap;

internal static class ScriptFileTemplates {
    public static readonly IReadOnlyList<string> DefaultUsings = [
        "System",
        "System.Collections.Generic",
        "System.Diagnostics",
        "System.IO",
        "System.Linq",
        "System.Text",
        "System.Text.RegularExpressions",
        "Autodesk.Revit.DB",
        "Autodesk.Revit.DB.Architecture",
        "Autodesk.Revit.DB.Electrical",
        "Autodesk.Revit.DB.Mechanical",
        "Autodesk.Revit.DB.Plumbing",
        "Autodesk.Revit.DB.Structure",
        "Autodesk.Revit.UI",
        "Pe.Revit.Scripting",
        "Pe.Revit.Scripting.Context",
        "Pe.Shared.RevitData",
        "Pe.Shared.RevitData.Schedules"
    ];

    public static string CreateProductReadme() =>
        $$"""
        # Pe.Tools

        This folder is the user-authored Pe.Tools content home.

        ## Folders

        - `{{ProductPathNames.SettingsDirectoryName}}/` - authored settings grouped by module.
        - `{{ProductPathNames.WorkspacesDirectoryName}}/` - Revit scripting workspaces.
        - `{{ProductPathNames.InlineScriptsDirectoryName}}/` - saved inline script traces from quick executions.
        - `{{ProductPathNames.OutputDirectoryName}}/` - generated user-visible command output.

        Runtime state, logs, caches, and installed binaries live under Local AppData, not this folder.
        """;

    public static string CreateProductAgents() =>
        $$"""
        # Pe.Tools User Content

        ## Scope

        Agent guidance for the Pe.Tools user-authored content home.

        ## Purpose

        This folder holds editable settings, scripting workspaces, inline script traces, and generated user output. Runtime state, logs, caches, and installed binaries live elsewhere.

        ## Entry Points

        - `{{ProductPathNames.SettingsDirectoryName}}/` - authored settings.
        - `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/` - scripting workspaces.
        - `{{ProductPathNames.InlineScriptsDirectoryName}}/` - retained inline snippet traces.
        - `{{ProductPathNames.OutputDirectoryName}}/` - durable user-visible output.

        ## Notes

        - Prefer workspace-relative script execution from `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/src/` for durable work.
        - Treat `{{ProductPathNames.InlineScriptsDirectoryName}}/` as trace history.
        - Settings are flattened as `{{ProductPathNames.SettingsDirectoryName}}/<module>/<root>/`.
        - Shared settings fragments and schemas belong under `{{ProductPathNames.SettingsDirectoryName}}/{{ProductPathNames.GlobalDirectoryName}}/`.
        """;

    public static string CreateReadme() =>
        """
        # Pe Revit Scripting

        This workspace is a Pod generated by Pe.Tools for Revit script authoring.

        Supported execution:

        - pod entrypoint scripts under `src/`, declared in `pod.json`
        - inline snippets, saved visibly in the product `inline-scripts/` folder
        - synchronous execution through the Pe.Tools Revit bridge

        Authoring contract:

        - Put durable scripts under `src/` as normal C# files and declare each runnable one in `pod.json` under `entrypoints`.
        - Run an entrypoint with `pea script execute --source-path src/MyScript.cs`.
        - Each entrypoint source file must contain exactly one non-abstract `PeScriptContainer`; helper `src/**/*.cs` files compile alongside but are not runnable.
        - Inline snippets may be Execute-body statements with optional leading `using` directives, or a full `PeScriptContainer` class.
        - Inside `Execute()`, use `doc`, `uidoc`, `app`, `selection`, `revitVersion`, `ct`, `Artifacts`, `Result(...)`, `WriteLine(...)`, and `Notify(...)` (progress messages pushed to the caller mid-run).
        - `ReadOnly` (the default) runs inside a rollback guard: document changes are discarded and reported as a warning. Use `WriteTransaction` to keep changes.
        - Long-running scripts should check `ct` (or call `ThrowIfCancelled()`) inside loops so cancellation and the execution timeout can interrupt them.
        - Use `Result(...)` once per run to return structured JSON to the caller; `WriteLine(...)` for short human-readable output; `Artifacts.WriteJson/WriteCsv/WriteText(...)` for durable files.
        - Add local DLL refs and `PackageReference` items in `PeScripts.csproj`.
        - Use host/agent tools outside the script to discover operation shapes; scripts should do direct bounded Revit API work.

        Non-goals for this workspace:

        - arbitrary local file execution outside the workspace
        - compiled DLL/package payload execution
        - async scripting sessions
        """;

    public static string CreateJoinGuide() =>
        """
        # Revit Script Orientation

        Scripts execute inside Revit through the Pe.Tools bridge.

        Use this file as orientation only. Prefer the live tool schemas, generated operation metadata, compiler diagnostics, and runtime results over memorized workflows.

        ## Surfaces

        - Direct Revit API access is available inside this Revit-hosted script for bounded document work and API gaps.
        - `Artifacts` writes durable CSV/JSON/text output under product output.

        ## Boundaries

        - Current script execution runs inside Revit through one bridge request; a second request waits up to 30s for the slot, then fails with a busy error.
        - `ReadOnly` is the default permission mode: the script runs inside a rollback guard, so any document changes are discarded and reported as a warning.
        - `WriteTransaction` is explicit and host-owned: one transaction, committed on success, rolled back if the script throws.
        - Executions have a cooperative timeout (default 600s) and can be cancelled with `scripting.cancel`; scripts that never check `ct` cannot be interrupted.
        - Keep terminal output small; use `Result(...)` for structured data and artifacts for broad rows, tables, or evidence.
        """;

    public static string CreateAgents() =>
        $$"""
        # Revit Scripting Workspace

        ## Scope

        Agent guidance for a generated scripting workspace under product `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/`.

        ## Purpose

        This workspace exists for small Revit-side C# scripts that execute through Pe.Tools scripting.

        ## Entry Points

        - `pod.json` - pod manifest declaring runnable entrypoints.
        - `PeScripts.csproj` - preserved DLL and package references.
        - `src/` - workspace scripts.
        - `src/SampleScript.cs` - minimal executable example.
        - `.vscode/settings.json` - generated editor hint.
        - `README.md` - human-facing bootstrap notes.
        - `JOIN_GUIDE.md` - Revit script orientation.

        ## Contract

        - Every workspace is a Pod: `pod.json` is validated, all `src/**/*.cs` compile together, and only declared entrypoints are runnable.
        - Execute an entrypoint with `pea script execute --source-path src/YourScript.cs`; add new scripts to `pod.json` under `entrypoints` first.
        - Each entrypoint source file must resolve to exactly one non-abstract `PeScriptContainer`; helper `src` files are compiled but are not entrypoints.
        - Inline snippets may be Execute-body statements with optional leading `using` directives, or a full `PeScriptContainer` class.
        - Inside `Execute()`, use `doc`, `uidoc`, `app`, `selection`, `revitVersion`, `ct`, `Artifacts`, `Result(...)`, `WriteLine(...)`, and `Notify(...)` (progress messages pushed to the caller mid-run).
        - Use `Result(...)` once per run for structured JSON results, `WriteLine(...)` for short diagnostics, and `Artifacts` for durable output.
        - Check `ct` (or call `ThrowIfCancelled()`) inside loops so timeouts and scripting.cancel can interrupt the script.
        - Add supported references through `PeScripts.csproj`.
        - Re-run workspace bootstrap after Revit version changes or missing generated references.

        ## Notes

        - Inline snippets are traceable probes, not the primary durable authoring surface.
        - `ReadOnly` (default) runs inside a rollback guard: document changes are discarded and reported as a warning; use `WriteTransaction` to keep changes.
        - The generated project preserves supported user references across bootstrap regeneration.
        - Use host/agent tools outside the script to discover operation shapes; keep scripts focused on direct Revit API work.
        - This workspace runs inside Revit through the Pe.Tools bridge; runtime behavior depends on the loaded Revit-side assemblies.
        """;

    public static string CreateVscodeSettings() =>
        """
        {
          "dotnet.defaultSolution": "PeScripts.csproj",
          "files.exclude": {
            "**/bin": true,
            "**/obj": true
          }
        }
        """;

    public static string CreateSampleScript() =>
        """
        // Run from this workspace root:
        // pea script execute --source-path src/SampleScript.cs
        //
        // This file is declared as an entrypoint in pod.json.
        // Keep exactly one non-abstract PeScriptContainer per entrypoint file.

        public sealed class SampleScript : PeScriptContainer
        {
            public override void Execute()
            {
                WriteLine($"Running in Revit {revitVersion}.");

                if (doc == null)
                {
                    WriteLine("No active document.");
                    return;
                }

                // Check ct in loops so timeouts and scripting.cancel can interrupt long work.
                ThrowIfCancelled();

                // Result(...) returns structured JSON to the caller; Artifacts writes durable files.
                Result(new
                {
                    document = doc.Title,
                    revitVersion,
                    selectedElementCount = selection.Count
                });
            }
        }
        """;

    public static string CreatePodManifest(string workspaceKey) =>
        $$"""
        {
          "schemaVersion": 1,
          "id": "{{workspaceKey}}",
          "name": "{{workspaceKey}}",
          "version": "0.1.0",
          "entrypoints": [
            {
              "id": "sample",
              "sourcePath": "src/SampleScript.cs",
              "name": "Sample Script",
              "description": "Minimal example: reports the active document as a structured result."
            }
          ]
        }
        """;
}
