using Pe.Shared.Product;

namespace Pe.Revit.Scripting.Bootstrap;

internal static class ScriptFileTemplates {
    public static readonly IReadOnlyList<string> DefaultUsings = [
        "System",
        "System.Collections.Generic",
        "System.Diagnostics",
        "System.IO",
        "System.Linq",
        "System.Text",
        "System.Text.RegularExpressions",
        "Autodesk.Revit.DB",
        "Autodesk.Revit.DB.Architecture",
        "Autodesk.Revit.DB.Electrical",
        "Autodesk.Revit.DB.Mechanical",
        "Autodesk.Revit.DB.Plumbing",
        "Autodesk.Revit.DB.Structure",
        "Autodesk.Revit.UI",
        "Pe.Revit.Scripting",
        "Pe.Revit.Scripting.Context",
        "Pe.Shared.HostContracts"
    ];

    public static string CreateProductReadme() =>
        $$"""
        # Pe.Tools

        This folder is the user-authored Pe.Tools content home.

        ## Folders

        - `{{ProductPathNames.SettingsDirectoryName}}/` - authored settings grouped by module.
        - `{{ProductPathNames.WorkspacesDirectoryName}}/` - Revit scripting workspaces.
        - `{{ProductPathNames.InlineScriptsDirectoryName}}/` - saved inline script traces from quick executions.
        - `{{ProductPathNames.OutputDirectoryName}}/` - generated user-visible command output.

        Runtime state, logs, caches, and installed binaries live under Local AppData, not this folder.
        """;

    public static string CreateProductAgents() =>
        $$"""
        # Pe.Tools User Content

        ## Scope

        Agent guidance for the Pe.Tools user-authored content home.

        ## Purpose

        This folder is for editable settings, Revit scripting workspaces, visible inline script traces, and generated user output. Keep runtime state, logs, caches, and installed binaries out of this tree.

        ## Critical Entry Points

        - `{{ProductPathNames.SettingsDirectoryName}}/` - authored settings by module; shared global files live under `{{ProductPathNames.SettingsDirectoryName}}/{{ProductPathNames.GlobalDirectoryName}}/`.
        - `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/` - source-first Revit scripting workspaces.
        - `{{ProductPathNames.InlineScriptsDirectoryName}}/` - retained inline snippet traces for review and promotion into a workspace.
        - `{{ProductPathNames.OutputDirectoryName}}/` - durable user-visible command output.

        ## Living Memory

        - Prefer workspace-relative script execution from `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/src/` for anything durable.
        - Treat `{{ProductPathNames.InlineScriptsDirectoryName}}/` as trace history, not the primary authoring surface.
        - Settings are flattened as `{{ProductPathNames.SettingsDirectoryName}}/<module>/<root>/`; do not recreate `{{ProductPathNames.SettingsDirectoryName}}/<module>/settings/<root>/`.
        - Shared settings fragments and schemas belong under `{{ProductPathNames.SettingsDirectoryName}}/{{ProductPathNames.GlobalDirectoryName}}/`.
        """;

    public static string CreateReadme() =>
        """
        # Pe Revit Scripting

        This workspace is generated by `Pe.Tools` for Revit script authoring.

        Current supported execution:

        - workspace-path execution for scripts under `src/`
        - inline snippets, saved visibly in the product `inline-scripts/` folder
        - sync execution through `Pe.Host` from the CLI or frontend

        Current non-goals:

        - no package/source-bundle execution
        - no arbitrary local file execution outside the workspace
        - no scripting SSE or async execution sessions

        Workflow:

        - Put container scripts under `src/`.
        - Derive exactly one non-abstract type from `PeScriptContainer`.
        - Run scripts from the CLI with `pea script execute --source-path src\MyProbe.cs`.
        - The CLI posts to `Pe.Host`, and the host forwards the request into Revit.
        - Add local DLL refs and `PackageReference` items in `PeScripts.csproj`.
        - `PeHostClient` is available by default through the generated shared runtime references.
        - Prefer `WriteLine(...)` for output. `Console.WriteLine(...)` is supported as a compatibility path.
        - Bootstrap can regenerate the project file without deleting your custom references.

        Future direction:

        - source-package sharing is the north star, but it is not supported yet
        """;

    public static string CreateAgents() =>
        $$"""
        # Revit Scripting Workspace

        ## Scope

        Agent guidance for a generated `Pe.Revit.Scripting` authoring workspace under product `{{ProductPathNames.WorkspacesDirectoryName}}/<key>/`.

        ## Purpose

        This workspace exists for quick Revit-side script authoring, ad hoc API experiments, and small shareable snippets that execute through `Pe.Tools` scripting.

        ## Critical Entry Points

        - `PeScripts.csproj` - preserved local DLL references, `PackageReference` items, and runtime assembly reference.
        - `src/` - author container scripts here.
        - `src/SampleScript.cs` - minimal executable example for the current runtime contract.
        - `.vscode/settings.json` - generated editor hint for this workspace.
        - `README.md` - short human-facing bootstrap notes.

        ## Validation

        - Derive exactly one non-abstract type from `PeScriptContainer` per execute request.
        - The daily product path is workspace-first execution. Keep supported scripts under `src/` and run them with `pea script execute --source-path src\YourScript.cs`.
        - The script runner discovers exactly one `PeScriptContainer` type per request and executes that container.
        - Prefer explicit `WriteLine(...)` output for diagnostics you want returned to the caller.
        - `Console.WriteLine(...)` is supported as a compatibility path, not the preferred API.
        - Add external DLLs with `<Reference><HintPath>...` and NuGet dependencies with `<PackageReference ... />` in `PeScripts.csproj`.
        - Re-run workspace bootstrap after Revit version changes so the generated project keeps the correct target framework and runtime assembly path.

        ## Living Memory

        - This setup is container-only. Top-level statements and Launchpad globals are intentionally not supported.
        - Current workspace execution compiles the whole `src/` tree and executes the selected file's single concrete `PeScriptContainer`. Source-package execution is future-facing and intentionally unsupported in this slice.
        - `PeHostClient` is part of the default generated scripting references. Use it directly instead of hand-rolling host HTTP calls in script code.
        - Keep assembly references explicit by default. Ambient probing of already-loaded Revit-process assemblies is an advanced troubleshooting path, not the normal authoring contract.
        - The public scripting surface is `Pe.Host`; runtime execution happens inside Revit through the private Host/Revit bridge.
        - Host scripting currently requires exactly one connected Revit bridge session.
        - If runtime behavior diverges from source during RRD, stale deployed assemblies are a plausible cause.
        - The generated project preserves user-authored DLL and package references across bootstrap regeneration, but it does not preserve arbitrary project-file customization beyond the supported workspace/project flow.
        - Keep scripts small and composable. Promote durable helpers into real repo packages instead of growing one-off script infrastructure here.
        """;

    public static string CreateVscodeSettings() =>
        """
        {
          "dotnet.defaultSolution": "PeScripts.csproj",
          "files.exclude": {
            "**/bin": true,
            "**/obj": true
          }
        }
        """;

    public static string CreateSampleScript() =>
        """
        // Run from this workspace root:
        // pea script execute --source-path src\SampleScript.cs
        //
        // IntelliSense tip:
        // Define exactly one non-abstract PeScriptContainer per execute request.
        // That container is the entry point the script runner discovers and executes.

        public sealed class SampleScript : PeScriptContainer
        {
            public override void Execute()
            {
                WriteLine($"Running in Revit {revitVersion}.");

                if (doc == null)
                {
                    TaskDialog.Show("Pe Script", "No active document.");
                    return;
                }

                TaskDialog.Show("Pe Script", $"Active document: {doc.Title}");
            }
        }
        """;
}
