namespace Pe.Revit.Scripting.Bootstrap;

internal static class ScriptFileTemplates {
    public static readonly IReadOnlyList<string> DefaultUsings = [
        "System",
        "System.Collections.Generic",
        "System.Diagnostics",
        "System.IO",
        "System.Linq",
        "System.Text",
        "System.Text.RegularExpressions",
        "Autodesk.Revit.DB",
        "Autodesk.Revit.DB.Architecture",
        "Autodesk.Revit.DB.Electrical",
        "Autodesk.Revit.DB.Mechanical",
        "Autodesk.Revit.DB.Plumbing",
        "Autodesk.Revit.DB.Structure",
        "Autodesk.Revit.UI",
        "Pe.Revit.Scripting"
    ];

    public static string CreateReadme() =>
        """
        # Pe Revit Scripting

        This workspace is generated by `Pe.Tools` for Revit script authoring.

        Current supported execution:

        - single-file workspace scripts under `src/`
        - inline snippets
        - sync execution through `Pe.Host` from the CLI or frontend

        Current non-goals:

        - no multi-file execution
        - no package/source-bundle execution
        - no arbitrary local file execution outside the workspace
        - no scripting SSE or async execution sessions

        Workflow:

        - Put container scripts under `src/`.
        - Derive exactly one non-abstract type from `PeScriptContainer`.
        - Run scripts from the CLI with `pe-script src\MyProbe.cs`.
        - The CLI posts to `Pe.Host`, and the host forwards the request into Revit.
        - Add local DLL refs and `PackageReference` items in `PeScripts.csproj`.
        - Prefer `WriteLine(...)` for output. `Console.WriteLine(...)` is supported as a compatibility path.
        - Bootstrap can regenerate the project file without deleting your custom references.

        Future direction:

        - source-package sharing is the north star, but it is not supported yet
        """;

    public static string CreateAgents() =>
        """
        # Revit Scripting Workspace

        ## Scope

        Agent guidance for the generated `Pe.Revit.Scripting` authoring workspace under `Documents\Pe.Scripting`.

        ## Purpose

        This workspace exists for quick Revit-side script authoring, ad hoc API experiments, and small shareable snippets that execute through `Pe.Tools` scripting.

        ## Critical Entry Points

        - `PeScripts.csproj` - preserved local DLL references, `PackageReference` items, and runtime assembly reference.
        - `src/` - author container scripts here.
        - `src/SampleScript.cs` - minimal executable example for the current runtime contract.
        - `AiGeneratedSnippets/` - intended landing area for generated or shared snippets.
        - `README.md` - short human-facing bootstrap notes.

        ## Validation

        - Derive exactly one non-abstract type from `PeScriptContainer` per execute request.
        - The daily product path is workspace-first single-file execution. Keep supported scripts under `src/` and run them with `pe-script <workspace-relative-script.cs>`.
        - The script runner discovers exactly one `PeScriptContainer` type per request and executes that container.
        - Prefer explicit `WriteLine(...)` output for diagnostics you want returned to the caller.
        - `Console.WriteLine(...)` is supported as a compatibility path, not the preferred API.
        - Add external DLLs with `<Reference><HintPath>...` and NuGet dependencies with `<PackageReference ... />` in `PeScripts.csproj`.
        - Re-run workspace bootstrap after Revit version changes so the generated project keeps the correct target framework and runtime assembly path.

        ## Living Memory

        - This setup is container-only. Top-level statements and Launchpad globals are intentionally not supported.
        - Current supported file execution is single-file only. Multi-file/source-package execution is future-facing and intentionally unsupported in this slice.
        - Keep assembly references explicit by default. Ambient probing of already-loaded Revit-process assemblies is an advanced troubleshooting path, not the normal authoring contract.
        - The public scripting surface is `Pe.Host`, but runtime execution still happens inside Revit through the internal scripting pipe.
        - Host scripting currently requires exactly one connected Revit bridge session.
        - If runtime behavior diverges from source during RR debug, stale deployed assemblies are a plausible cause.
        - The generated project preserves user-authored DLL and package references across bootstrap regeneration, but it does not preserve arbitrary project-file customization beyond the supported workspace/project flow.
        - Keep scripts small and composable. Promote durable helpers into real repo packages instead of growing one-off script infrastructure here.
        """;

    public static string CreateVscodeSettings() =>
        """
        {
          "dotnet.defaultSolution": "PeScripts.csproj",
          "files.exclude": {
            "**/bin": true,
            "**/obj": true
          }
        }
        """;

    public static string CreateSampleScript() =>
        """
        // Run from this workspace root:
        // pe-script src\SampleScript.cs
        //
        // IntelliSense tip:
        // Define exactly one non-abstract PeScriptContainer per execute request.
        // That container is the entry point the script runner discovers and executes.

        public sealed class SampleScript : PeScriptContainer
        {
            public override void Execute()
            {
                WriteLine($"Running in Revit {revitVersion}.");

                if (doc == null)
                {
                    TaskDialog.Show("Pe Script", "No active document.");
                    return;
                }

                TaskDialog.Show("Pe Script", $"Active document: {doc.Title}");
            }
        }
        """;
}
