<Project Sdk="Pe.Revit.Sdk">

    <PropertyGroup>
        <PeProjectKind>Explicit</PeProjectKind>
        <TargetFramework>net8.0-windows7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pe.Revit.Takeoff\Pe.Revit.Takeoff.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\eng\PrivateFixtures.cs" Link="PrivateFixtures.cs" />
    </ItemGroup>

</Project>
