// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from Pe.Shared.HostContracts.Bridge and Protocol.

import { Schema } from "effect";

export const HOST_CONTRACT_VERSION = 35 as const;
export const BRIDGE_CONTRACT_VERSION = 19 as const;
export const BRIDGE_PATH = "/api/bridge" as const;

const nullableString = Schema.optional(Schema.NullOr(Schema.String));

export const hostModuleDescriptorSchema = Schema.Struct({
  activeDocumentKind: Schema.Literals(["Any", "ProjectOnly", "FamilyOnly"]),
  defaultRootKey: Schema.String,
  moduleKey: Schema.String,
  scope: Schema.Literals(["Host", "Session", "ActiveDocument"]),
});
export type HostModuleDescriptor = Schema.Schema.Type<typeof hostModuleDescriptorSchema>;

export const hostRuntimeAssemblyDataSchema = Schema.Struct({
  informationalVersion: nullableString,
  location: nullableString,
  moduleVersionId: Schema.String,
  name: Schema.String,
  version: nullableString,
});
export type HostRuntimeAssemblyData = Schema.Schema.Type<typeof hostRuntimeAssemblyDataSchema>;

export const performanceMetricsSchema = Schema.Struct({
  requestBytes: Schema.Number,
  responseBytes: Schema.Number,
  revitExecutionMs: Schema.Number,
  roundTripMs: Schema.Number,
  serializationMs: Schema.Number,
});
export type PerformanceMetrics = Schema.Schema.Type<typeof performanceMetricsSchema>;

export const validationIssueSchema = Schema.Struct({
  code: Schema.String,
  instancePath: Schema.String,
  message: Schema.String,
  schemaPath: nullableString,
  severity: Schema.String,
  suggestion: nullableString,
});
export type ValidationIssue = Schema.Schema.Type<typeof validationIssueSchema>;

export const bridgeEventSchema = Schema.Struct({
  eventName: Schema.String,
  payloadJson: Schema.String,
});
export type BridgeEvent = Schema.Schema.Type<typeof bridgeEventSchema>;

export const bridgeRegistrationAckSchema = Schema.Struct({
  accepted: Schema.Boolean,
  errorMessage: nullableString,
});
export type BridgeRegistrationAck = Schema.Schema.Type<typeof bridgeRegistrationAckSchema>;

export const bridgeStateSnapshotSchema = Schema.Struct({
  activeDocumentCloudModelGuid: nullableString,
  activeDocumentCloudModelUrn: nullableString,
  activeDocumentCloudProjectGuid: nullableString,
  activeDocumentIsFamilyDocument: Schema.Boolean,
  activeDocumentIsModelInCloud: Schema.Boolean,
  activeDocumentIsWorkshared: Schema.Boolean,
  activeDocumentKey: nullableString,
  activeDocumentObservedAtUnixMs: Schema.Number,
  activeDocumentPath: nullableString,
  activeDocumentTitle: nullableString,
  availableModules: Schema.Array(hostModuleDescriptorSchema),
  hasActiveDocument: Schema.Boolean,
  openDocumentCount: Schema.Number,
  revitVersion: Schema.String,
  runtimeAssemblies: Schema.Array(hostRuntimeAssemblyDataSchema),
  runtimeFramework: Schema.String,
  sharedParametersFilename: nullableString,
});
export type BridgeStateSnapshot = Schema.Schema.Type<typeof bridgeStateSnapshotSchema>;

export const bridgeRegistrationRequestSchema = Schema.Struct({
  contractVersion: Schema.Number,
  processId: Schema.Number,
  state: bridgeStateSnapshotSchema,
});
export type BridgeRegistrationRequest = Schema.Schema.Type<typeof bridgeRegistrationRequestSchema>;

export const bridgeRequestSchema = Schema.Struct({
  operationKey: Schema.String,
  payloadJson: Schema.String,
  requestId: Schema.String,
});
export type BridgeRequest = Schema.Schema.Type<typeof bridgeRequestSchema>;

export const bridgeResponseSchema = Schema.Struct({
  errorMessage: nullableString,
  issues: Schema.optional(Schema.NullOr(Schema.Array(validationIssueSchema))),
  metrics: performanceMetricsSchema,
  ok: Schema.Boolean,
  payloadJson: nullableString,
  requestId: Schema.String,
  statusCode: Schema.optional(Schema.NullOr(Schema.Number)),
});
export type BridgeResponse = Schema.Schema.Type<typeof bridgeResponseSchema>;

export const bridgeStateSyncSchema = Schema.Struct({
  state: bridgeStateSnapshotSchema,
});
export type BridgeStateSync = Schema.Schema.Type<typeof bridgeStateSyncSchema>;

export const bridgeFrameSchema = Schema.Struct({
  disconnectReason: nullableString,
  event: Schema.optional(Schema.NullOr(bridgeEventSchema)),
  kind: Schema.Literals([
    "Registration",
    "RegistrationAck",
    "StateSync",
    "Request",
    "Response",
    "Event",
    "Disconnect",
  ]),
  registration: Schema.optional(Schema.NullOr(bridgeRegistrationRequestSchema)),
  registrationAck: Schema.optional(Schema.NullOr(bridgeRegistrationAckSchema)),
  request: Schema.optional(Schema.NullOr(bridgeRequestSchema)),
  response: Schema.optional(Schema.NullOr(bridgeResponseSchema)),
  stateSync: Schema.optional(Schema.NullOr(bridgeStateSyncSchema)),
});
export type BridgeFrame = Schema.Schema.Type<typeof bridgeFrameSchema>;
