// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from Pe.Shared.HostContracts.Operations.

export type HostHttpVerb = "GET" | "POST";
export type HostExecutionMode = "Local" | "Bridge";
export type HostOperationExposure = "PublicHttp" | "InternalHostOnly";
export type HostOperationIntent = "Read" | "Mutate";
export type HostOperationFamily = "Host" | "Settings" | "Script" | "Revit" | "Aps";
export type RevitOperationLayer = "Context" | "Catalog" | "Matrix" | "Detail" | "Resolve" | "Apply";
export type RevitActiveDocumentKind = "Project" | "Family";
export type HostOperationCostTier = "Cheap" | "Bounded" | "Expensive" | "Mutation";
export type HostOperationVisibility = "DefaultVisible" | "EscalationVisible" | "ExpertOnly";
export type HostOperationRelationKind = "Preflight" | "DrillDown" | "Fallback" | "Alternative";
export type HostErrorKind =
  | "Disconnected"
  | "BridgeBusy"
  | "InvalidRequest"
  | "Conflict"
  | "HostFailure";

export interface HostOperationRequestExample {
  name: string;
  description: string;
  json: string;
}

export interface HostOperationRelatedOperation {
  key: string;
  kind: HostOperationRelationKind;
  note?: string | null;
}

export interface HostOperationDefinition {
  key: string;
  verb: HostHttpVerb;
  route: string;
  executionMode: HostExecutionMode;
  exposure?: HostOperationExposure;
  requestTypeName?: string;
  responseTypeName?: string;
  displayName?: string;
  domain?: string;
  description?: string;
  searchTerms?: readonly string[];
  intent?: HostOperationIntent;
  requiresBridge?: boolean;
  requiresActiveDocument?: boolean;
  supportedActiveDocumentKinds?: readonly RevitActiveDocumentKind[];
  family?: HostOperationFamily;
  revitLayer?: RevitOperationLayer | null;
  domainNoun?: string;
  costTier?: HostOperationCostTier;
  visibility?: HostOperationVisibility;
  singleFlightGroup?: string | null;
  requestExamples?: readonly HostOperationRequestExample[];
  safeDefaultRequestJson?: string | null;
  callGuidance?: readonly string[];
  relatedOperations?: readonly HostOperationRelatedOperation[];
  strictRequestValidation?: boolean;
}

export interface HostCapabilityMapRow {
  key: string;
  description: string;
  safety: string;
  inputKind: string;
  outputKind: string;
  terms: string;
}

export interface HostCapabilityMapSection {
  id: string;
  title: string;
  summary: string;
  rows: readonly HostCapabilityMapRow[];
}

export interface HostCapabilityMap {
  generatedFrom: string;
  formatVersion: number;
  rowCount: number;
  guidance: string;
  operationKeys: readonly string[];
  sections: readonly HostCapabilityMapSection[];
  focusSections: readonly HostCapabilityMapSection[];
}
