// <auto-generated />
// Generated by `pe-dev codegen sync --target host-contracts` from HostOperationsCatalog.PublicHttp.

import type { HostCapabilityMap } from "./host-operation-contracts.generated.js";

export const hostCapabilityMap = {
  generatedFrom: "HostOperationsCatalog.PublicHttp",
  formatVersion: 1,
  rowCount: 46,
  guidance:
    "Table-of-contents routing map only. Use sections to choose a capability ladder; use host_operation_search matches for call guidance and exact request/response shapes.",
  operationKeys: [
    "aps.auth.login",
    "aps.auth.logout",
    "aps.auth.status",
    "aps.auth.token",
    "host.logs",
    "revit.apply.document.open",
    "revit.catalog.concept-evidence",
    "revit.catalog.electrical-circuits",
    "revit.catalog.electrical-load-classifications",
    "revit.catalog.electrical-panels",
    "revit.catalog.loaded-families",
    "revit.catalog.loaded-families.filter-field-options",
    "revit.catalog.loaded-families.filter-schema",
    "revit.catalog.parameter-bindings",
    "revit.catalog.parameter-evidence",
    "revit.catalog.project-browser",
    "revit.catalog.project-index",
    "revit.catalog.recent-documents",
    "revit.catalog.schedules",
    "revit.context.document-session",
    "revit.context.summary",
    "revit.context.view-rendering-state",
    "revit.context.visible-summary",
    "revit.detail.electrical-panel-schedules",
    "revit.detail.elements",
    "revit.detail.schedules",
    "revit.detail.sheets",
    "revit.matrix.loaded-families",
    "revit.matrix.parameter-coverage",
    "revit.matrix.schedule-coverage",
    "revit.matrix.schedule-profiles",
    "revit.resolve.references",
    "scripting.execute",
    "scripting.pod.export",
    "scripting.pod.import",
    "scripting.workspace.bootstrap",
    "settings.document.open",
    "settings.document.save",
    "settings.document.validate",
    "settings.field-options",
    "settings.host-probe",
    "settings.parameter-catalog",
    "settings.schema",
    "settings.session-summary",
    "settings.tree",
    "settings.workspaces",
  ],
  sections: [
    {
      id: "context",
      title: "Context",
      summary: "Cheap current Revit document, active view, selection, and session orientation.",
      rows: [
        {
          key: "revit.context.document-session",
          description:
            "Read open, active, and selected document session context from connected Revit.",
          safety: "Bridge, Cheap",
          inputKind: "none",
          outputKind: "current state summary",
          terms: "document|session|active-document|open-documents",
        },
        {
          key: "revit.context.summary",
          description:
            "Read compact current document, active view or sheet, selection, browser counts, and visible-category context for Pea orientation.",
          safety: "Bridge, active-doc, Cheap, Project|Family",
          inputKind: "none",
          outputKind: "current state summary",
          terms: "agent-context|summary|active-view|selection|visible|browser",
        },
        {
          key: "revit.context.view-rendering-state",
          description:
            "Read a bounded evidence packet for visibility/rendering-affecting state in the active view or explicit views, including explicit limitations and uninspected causes.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "context scope",
          outputKind: "current state summary",
          terms:
            "agent-context|view-rendering|visibility|active-view|view-references|filters|links|worksets|view-range|crop|template",
        },
        {
          key: "revit.context.visible-summary",
          description:
            "Read compact category counts and bounded visible element handles for the active view or explicit view references.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "context scope",
          outputKind: "current state summary",
          terms:
            "agent-context|visible|active-view|view-references|categories|handles|printed-views|visible-equipment",
        },
      ],
    },
    {
      id: "catalog",
      title: "Catalog",
      summary:
        "Cheap/bounded inventories of candidate schedules, families, parameters, browser paths, and model nouns.",
      rows: [
        {
          key: "revit.catalog.concept-evidence",
          description:
            "Infer project-specific parameter candidates for operator concepts from factual binding and schedule evidence. Category and subject hints are weak context, not expected-shape rules; use returned reasons and facts before detail or coverage calls.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "concepts|parameter-evidence|project-standards|bindings|schedule-fields|discovery",
        },
        {
          key: "revit.catalog.electrical-circuits",
          description:
            "Read electrical circuit facts, connected load identity, panel names, circuit numbers, optional nearby proxy context, and compact filter diagnostics from the active Revit document.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms:
            "revit|circuits|catalog|loads|panel|load-name|connected-elements|nearby-proxy|equipment-alignment",
        },
        {
          key: "revit.catalog.electrical-load-classifications",
          description: "Read electrical load classification facts from the active Revit document.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "revit|load-classifications|catalog|loads",
        },
        {
          key: "revit.catalog.electrical-panels",
          description:
            "Read electrical panel facts, panel names, marks, panel-schedule counts, connected-load counts, and compact filter diagnostics from the active Revit document.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms:
            "revit|panels|catalog|distribution|electrical-equipment|panel-schedule-references|panel-names",
        },
        {
          key: "revit.catalog.loaded-families",
          description: "Read loaded family and type facts from the active document.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "loaded-families|families|types|catalog",
        },
        {
          key: "revit.catalog.loaded-families.filter-field-options",
          description: "Read document-specific option values for loaded-family query filters.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "loaded-families|families|filter|field-options",
        },
        {
          key: "revit.catalog.loaded-families.filter-schema",
          description: "Read the filter schema for loaded-family catalog and matrix queries.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "none",
          outputKind: "candidate handles/list",
          terms: "loaded-families|families|filter|schema",
        },
        {
          key: "revit.catalog.parameter-bindings",
          description:
            "Read project parameter bindings from the active document, using the same canonical parameter identity and shared-GUID string language returned by parameter evidence and coverage operations.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms:
            "parameters|project-parameters|bindings|document|catalog|parameter-identity|shared-guid",
        },
        {
          key: "revit.catalog.parameter-evidence",
          description:
            "Return factual parameter evidence from project bindings, schedule fields/filters, and scoped element presence. Use this when project-standard parameter names are uncertain; inspect binding categories, schedule usage, counts, and samples, then pass observed parameter identities or named references into detail or matrix calls.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "parameters|evidence|project-bindings|schedule-fields|categories|parameter-usage",
        },
        {
          key: "revit.catalog.project-browser",
          description:
            "Read bounded Project Browser organization for views, sheets, and schedules as navigation/provenance metadata.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "project-browser|browser|views|sheets|schedules|folders|navigation|provenance",
        },
        {
          key: "revit.catalog.project-index",
          description:
            "Read a compact semantic project index with bounded Project Browser provenance for levels, sheets, views, schedules, categories, and families.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms:
            "project-index|project-browser|browser-provenance|levels|sheets|views|schedules|printed-context|orientation",
        },
        {
          key: "revit.catalog.recent-documents",
          description:
            "Read local Revit recent-document candidates from user Revit.ini files without requiring a connected Revit session. The current opener supports local files only; cloud recent entries are preserved in the contract for later cloud open support but omitted by default.",
          safety: "Local, Cheap",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms: "document|recent|revit-ini|local-files|catalog",
        },
        {
          key: "revit.catalog.schedules",
          description:
            "Read compact schedule handles, names, sheet placement, optional field metadata, and factual schedule evidence summaries from the active document. Revit-generated duplicate suffixes like \u0027(2)\u0027 and \u0027Copy 1\u0027 are normalized out of name summary weighting. Do not use broad schedule catalog discovery for visible equipment coverage when revit.matrix.schedule-coverage can answer from view or element handles.",
          safety: "Bridge, active-doc, Cheap, Project",
          inputKind: "bounded filters",
          outputKind: "candidate handles/list",
          terms:
            "schedules|catalog|fields|columns|parameters|document|sheet-placement|printed-context",
        },
      ],
    },
    {
      id: "matrix",
      title: "Matrix",
      summary: "Bounded joins and audits after context/catalog narrowing.",
      rows: [
        {
          key: "revit.matrix.loaded-families",
          description:
            "Read a matrix projection of loaded family/type facts from the active document.",
          safety: "Bridge, active-doc, Expensive, Project",
          inputKind: "scoped audit query",
          outputKind: "join/audit results",
          terms: "loaded-families|families|matrix|projection|parameter-presence",
        },
        {
          key: "revit.matrix.parameter-coverage",
          description:
            "Read bounded parameter presence, blank/default counts, and sample handles from the active document.",
          safety: "Bridge, active-doc, Expensive, Project",
          inputKind: "scoped audit query",
          outputKind: "join/audit results",
          terms: "parameters|coverage|matrix|elements|handles",
        },
        {
          key: "revit.matrix.schedule-coverage",
          description:
            "Read bounded element-to-schedule coverage counts and samples from the active document, including active-view-visible or explicit-handle scopes.",
          safety: "Bridge, active-doc, Expensive, Project",
          inputKind: "scoped audit query",
          outputKind: "join/audit results",
          terms:
            "schedules|coverage|matrix|elements|handles|active-view-visible|explicit-handles|visible-equipment|printed-context",
        },
        {
          key: "revit.matrix.schedule-profiles",
          description: "Read schedule profile projections from the active document.",
          safety: "Bridge, active-doc, Expensive, Project",
          inputKind: "scoped audit query",
          outputKind: "join/audit results",
          terms: "schedules|profiles|query|projection|authored-schedule-shape",
        },
      ],
    },
    {
      id: "detail",
      title: "Detail",
      summary: "Exact inspection of known schedules, sheets, elements, rows, or panel schedules.",
      rows: [
        {
          key: "revit.detail.electrical-panel-schedules",
          description:
            "Read electrical panel schedule row/cell projections from the active Revit document. Use this for known panels/schedules, not as the first-choice element-to-load join.",
          safety: "Bridge, active-doc, Bounded, Project",
          inputKind: "known handles or filters",
          outputKind: "detail records",
          terms:
            "revit|panel-schedules|query|schedules|rows|cells|known-panel|panel-references|downstream-detail",
        },
        {
          key: "revit.detail.elements",
          description:
            "Read exact element context, selected/visible equipment facts, requested parameters, electrical systems, circuits, panels, connectors, panel schedules, load classifications, and nearby document facts from connected Revit.",
          safety: "Bridge, active-doc, Bounded, Project",
          inputKind: "known handles or filters",
          outputKind: "detail records",
          terms:
            "elements|selection|context|query|requested-parameters|electrical|circuits|panel|load-name|explicit-handles|visible-handles|selected-equipment|equipment-alignment",
        },
        {
          key: "revit.detail.schedules",
          description: "Read schedule rows and field values from the active document.",
          safety: "Bridge, active-doc, Bounded, Project",
          inputKind: "known handles or filters",
          outputKind: "detail records",
          terms: "schedules|query|rows|values|detail",
        },
        {
          key: "revit.detail.sheets",
          description:
            "Read minimal native sheet anchors for extractor and scripting workflows: sheet identity, placed views, placed schedules, title blocks, sheet-owned text, and provenance.",
          safety: "Bridge, active-doc, Bounded, Project",
          inputKind: "known handles or filters",
          outputKind: "detail records",
          terms:
            "sheets|sheet-anchors|printed-context|viewports|schedule-placement|title-blocks|text-notes|extractor-boundary",
        },
      ],
    },
    {
      id: "resolve",
      title: "Resolve",
      summary: "Fuzzy human references into stable handles before detail or matrix calls.",
      rows: [
        {
          key: "revit.resolve.references",
          description:
            "Resolve natural references like this view, selected equipment, or printed mech Level 1 plan into stable Revit handles with provenance; narrow by handle kind and printed context when the user already described the scope.",
          safety: "Bridge, active-doc, Bounded, Project",
          inputKind: "reference text/context",
          outputKind: "resolved references",
          terms:
            "agent-context|resolve|natural-reference|handles|provenance|printed-context|view-handles",
        },
      ],
    },
    {
      id: "apply",
      title: "Apply",
      summary: "Explicit host/Revit state changes after discovery and inspection.",
      rows: [
        {
          key: "revit.apply.document.open",
          description: "Open and activate a local Revit document in the connected Revit session.",
          safety: "Bridge, Mutation",
          inputKind: "explicit mutation request",
          outputKind: "mutation result",
          terms: "document|open|activate|cross-document",
        },
      ],
    },
    {
      id: "settings",
      title: "Settings",
      summary:
        "Schema-backed settings/profile authoring, validation, field options, and workspaces.",
      rows: [
        {
          key: "settings.document.open",
          description: "Read a settings document snapshot from the local settings workspace.",
          safety: "Local, Cheap",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "settings|document|open|snapshot|profile|profiles|family-foundry",
        },
        {
          key: "settings.document.save",
          description: "Write a settings document to the local settings workspace.",
          safety: "Local, Mutation",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "settings|document|save|write|profile|profiles|family-foundry",
        },
        {
          key: "settings.document.validate",
          description: "Validate a settings document and return diagnostics without saving it.",
          safety: "Local, Cheap",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms:
            "settings|document|validate|validation|diagnostics|profile|profiles|family-foundry",
        },
        {
          key: "settings.field-options",
          description: "Read document-specific field option values for a settings module.",
          safety: "Bridge, active-doc, Bounded",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "settings|field-options|schema|document",
        },
        {
          key: "settings.parameter-catalog",
          description:
            "Read Revit parameter definitions and available parameter facts from the active document for settings authoring.",
          safety: "Bridge, active-doc, Bounded",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "parameters|catalog|settings|document",
        },
        {
          key: "settings.schema",
          description: "Read a settings schema from the connected Revit runtime.",
          safety: "Bridge, active-doc, Bounded",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "schema|settings|profile|profiles|module|family-foundry",
        },
        {
          key: "settings.tree",
          description: "Read the local settings tree for profiles, modules, and documents.",
          safety: "Local, Cheap",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "settings|tree|discover|documents|profiles|family-foundry",
        },
        {
          key: "settings.workspaces",
          description: "Read available settings workspaces and storage roots.",
          safety: "Local, Cheap",
          inputKind: "settings/profile request",
          outputKind: "settings/profile result",
          terms: "settings|workspace|storage|roots",
        },
      ],
    },
    {
      id: "aps",
      title: "APS",
      summary: "Autodesk Platform Services auth and cloud workflow support operations.",
      rows: [
        {
          key: "aps.auth.login",
          description: "Start or complete Autodesk Platform Services authentication.",
          safety: "Local, Mutation",
          inputKind: "APS auth/cloud request",
          outputKind: "APS status/cloud result",
          terms: "aps|auth|login|token",
        },
        {
          key: "aps.auth.logout",
          description: "Clear persisted Autodesk Platform Services authentication state.",
          safety: "Local, Mutation",
          inputKind: "none",
          outputKind: "APS status/cloud result",
          terms: "aps|auth|logout|token",
        },
        {
          key: "aps.auth.status",
          description: "Read persisted Autodesk Platform Services authentication status.",
          safety: "Local, Cheap",
          inputKind: "APS auth/cloud request",
          outputKind: "APS status/cloud result",
          terms: "aps|auth|status|token",
        },
        {
          key: "aps.auth.token",
          description:
            "Acquire an Autodesk Platform Services access token for authenticated operations.",
          safety: "Local, Cheap",
          inputKind: "APS auth/cloud request",
          outputKind: "APS status/cloud result",
          terms: "aps|auth|access-token|token",
        },
      ],
    },
    {
      id: "host",
      title: "Host",
      summary: "Local host process, logs, probe, and session facts.",
      rows: [
        {
          key: "host.logs",
          description: "Read bounded host and Revit log tails for diagnosis.",
          safety: "Local, Cheap",
          inputKind: "host/session request",
          outputKind: "host/session facts",
          terms: "logs|diagnostics|host|revit",
        },
        {
          key: "settings.host-probe",
          description: "Read Pe.Host health, version, and compatibility facts.",
          safety: "Local, Cheap",
          inputKind: "none",
          outputKind: "settings/profile result",
          terms: "status|health|probe|compatibility",
        },
        {
          key: "settings.session-summary",
          description:
            "Read current host, bridge, session, active document, and workspace summary facts.",
          safety: "Local, Cheap",
          inputKind: "none",
          outputKind: "settings/profile result",
          terms: "status|session|bridge|active-document|workspace",
        },
      ],
    },
    {
      id: "script",
      title: "Scripting",
      summary: "Host-owned C# scripting workspace bootstrap and execution.",
      rows: [
        {
          key: "scripting.execute",
          description:
            "Execute an inline or workspace-relative C# script in connected Revit. Inline content may be Execute-body statements with optional leading using directives or a full PeScriptContainer class; workspace files are normal C# PeScriptContainer entrypoints.",
          safety: "Bridge, active-doc, Mutation",
          inputKind: "workspace/script request",
          outputKind: "workspace/script result",
          terms: "script|execute|csharp|revit",
        },
        {
          key: "scripting.pod.export",
          description:
            "Export a validated pod.json-backed Revit scripting workspace as a portable source-first zip archive.",
          safety: "Bridge, Mutation",
          inputKind: "workspace/script request",
          outputKind: "workspace/script result",
          terms: "script|pod|export|workspace|zip|archive",
        },
        {
          key: "scripting.pod.import",
          description:
            "Import a pod.json-backed Revit scripting workspace from a conservative zip archive into a new workspace slug.",
          safety: "Bridge, Mutation",
          inputKind: "workspace/script request",
          outputKind: "workspace/script result",
          terms: "script|pod|import|workspace|zip|archive",
        },
        {
          key: "scripting.workspace.bootstrap",
          description: "Create or update the host-owned C# Revit scripting workspace files.",
          safety: "Bridge, Mutation",
          inputKind: "workspace/script request",
          outputKind: "workspace/script result",
          terms: "script|workspace|bootstrap|files",
        },
      ],
    },
  ],
  focusSections: [],
} as const satisfies HostCapabilityMap;
