/**
 * Typegen: fetch the runtime op catalog from a running host (GET /ops, which
 * proxies host.ops.catalog to the connected Revit session) and emit one
 * TypeScript file with per-op request/response types, a runtime key list, and
 * a key→types map. The emitted file is CHECKED IN — it is the compile-time
 * contract artifact, committed like a lockfile.
 *
 * The running session is the source of truth — no C# reflection projection,
 * no [ExportTsSchema], no pe-dev codegen.
 *
 * Run (from packages/tools):
 *   node src/dev/host-typegen.ts                 # regenerate the checked-in file
 *   node src/dev/host-typegen.ts --check         # drift gate: exit 1 if stale
 *   [--host http://localhost:5180] [--session <bridgeSessionId>] [--out <path>]
 */
import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type CatalogEntry = {
  key: string;
  displayName?: string | null;
  intent: string;
  description: string;
  requestSchemaJson: string;
  responseSchemaJson: string;
};

function argValue(flag: string, fallback: string): string {
  const index = process.argv.indexOf(flag);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}

function pascalCase(key: string): string {
  return key
    .split(/[.\-_]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function indent(block: string): string {
  return block
    .split("\n")
    .map((line) => (line.trim() ? `  ${line}` : line))
    .join("\n");
}

// json-schema-to-typescript prefers the schema's root `title` (e.g. the C# type
// name) over the name argument; drop it so the root is always Request/Response.
function parseUntitled(schemaJson: string): Record<string, unknown> {
  const schema = JSON.parse(schemaJson) as Record<string, unknown>;
  delete schema.title;
  return schema;
}

const DEFAULT_OUT = resolve(
  import.meta.dirname,
  "../../../host-contracts/src/generated/host-ops.generated.ts",
);

const hostBase = argValue("--host", "http://localhost:5180");
const session = argValue("--session", "");
const outPath = argValue("--out", DEFAULT_OUT);
const checkMode = process.argv.includes("--check");

const url = `${hostBase}/ops${session ? `?session=${encodeURIComponent(session)}` : ""}`;
const response = await fetch(url);
if (!response.ok) {
  console.error(`GET ${url} failed: ${response.status} ${await response.text()}`);
  process.exit(1);
}
const catalog = (await response.json()) as { operations: CatalogEntry[] };
const operations = [...catalog.operations].sort((a, b) => a.key.localeCompare(b.key));

const chunks: string[] = [
  "/* eslint-disable */",
  "// Generated by host-typegen from a live host op catalog. Do not edit.",
  "// Regenerate: pnpm --filter @pe/tools exec node src/dev/host-typegen.ts",
  "// Drift gate: append --check (fails when this file no longer matches the live catalog).",
  "",
];
const mapEntries: string[] = [];

for (const op of operations) {
  const ns = pascalCase(op.key);
  const requestTs = await compile(parseUntitled(op.requestSchemaJson), "Request", {
    bannerComment: "",
    additionalProperties: false,
  });
  const responseTs = await compile(parseUntitled(op.responseSchemaJson), "Response", {
    bannerComment: "",
    additionalProperties: false,
  });
  chunks.push(
    `/** ${op.description} */`,
    `export namespace ${ns} {`,
    indent(`export namespace Req {\n${indent(requestTs.trim())}\n}`),
    indent(`export namespace Res {\n${indent(responseTs.trim())}\n}`),
    "}",
    "",
  );
  mapEntries.push(`  "${op.key}": { request: ${ns}.Req.Request; response: ${ns}.Res.Response };`);
}

chunks.push(
  "/** Key → request/response types for every bridge op the generating session supported. */",
  "export interface HostOps {",
  ...mapEntries,
  "}",
  "",
  "/** Runtime key list matching HostOps — powers key guards without a metadata catalog. */",
  "export const hostOpKeys = [",
  ...operations.map((op) => `  "${op.key}",`),
  "] as const satisfies readonly (keyof HostOps)[];",
  "",
);

const output = chunks.join("\n");

if (checkMode) {
  const existing = await readFile(outPath, "utf8").catch(() => null);
  if (existing === output) {
    console.log(`host-ops types are in sync with ${url} (${operations.length} operations).`);
    process.exit(0);
  }
  console.error(
    existing === null
      ? `${outPath} is missing. Run host-typegen without --check to generate it.`
      : `${outPath} is stale against the live catalog at ${url}. Run host-typegen to regenerate, review, and commit.`,
  );
  process.exit(1);
}

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, output, "utf8");
console.log(`Wrote ${operations.length} operations to ${outPath}`);
