packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: 0.2.0
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@google/genai": false
  "@makeomatic/ffi-napi": true
  "@makeomatic/ref-napi": true
  agent-browser: false
  bufferutil: false
  edgedriver: false
  geckodriver: false
  koffi: false
  onnxruntime-node: false
  protobufjs: false
minimumReleaseAgeExclude:
  - lucide-react@1.21.0
